### ISSUE TITLE
GD-112: Running tests in editor does not reveal compilation errors

### ISSUE THREAD

**Issue by Wcubed** [MikeSchulze/gdUnit3#112]
**Version** 1.0.0

**The used Godot version:** v3.3.2.stable.arch_linux

**OS including version:** Manjaro, kernel 5.20.49-1 (64 bit)

**Describe the bug**
When the code under test has a compilation error, running the tests normally (not in debug mode) will return green. This means that these test results are actually lying to us, because non-compiling code can by definition not complete the test :).

Running the tests in debug mode *does* break at the compilation error, so currently I only run tests this way.
The `runtest.sh -a` command does also break at the error and opens a debug prompt. However running with the `-c` option wont continue the testing (probably another bug report).

**Steps to Reproduce**
1. Open the test_gdunit project.
2. Run the tests in the `test` folder.
3. Note how the tests return green.
4. Run the tests in debug mode.
5. Note how line 6 in `Main.gd` does not actually compile. Meaning that the green test results from the non-debug run were actually lying to us.

**Minimal reproduction project:**
[test_gdunit.zip](https://github.com/MikeSchulze/gdUnit3/files/6861500/test_gdunit.zip)

**Comment by MikeSchulze** [comment]
Thanks for reporting.

Yes compile errors should end up in test errors. ;)

**Comment by MikeSchulze** [comment]
This is a problem with Godot and error reporting.
Calling `new` in a script that contains parse errors is only reported as an error internally, and I don't see any way to catch this. 

The only workaround would be to provide a custom load/instance function in GdUnit. This function could then catch this and generate an error based on this information.
However, this would read wonky and deviate from the standard how to load or instantiate a script.

I have experimented a bit.

```
func script_instance(resource_path :String) -> Object:
	var script = load(resource_path)
	if script.can_instance():
		return script.new()
	if script.reload() == ERR_PARSE_ERROR:
		return GdUnitAssertImpl.new(self, null).override_failure_message("The script `%s` can't be instanciate, possible parse errors!" % resource_path).test_fail()
	return GdUnitAssertImpl.new(self, null).override_failure_message("The script `%s` can't be instanciate, unknown error!" % resource_path).test_fail()

func test_add() -> void:
	var instance = script_instance("res://error_case/new_script.gd")
	
	
	assert_int(instance.add(1,2)).is_equal(3)

```

**Comment by Wcubed** [comment]
Hmm, that does indeed complicate things. The wrapper works as expected, but I agree it's less than ideal... I tried defining a `load` function in the hope that it would call that instead of the default, but as suspected, that does not work :P. What might be an option is creating a `_load()` function or something similar that wraps around the standard `load()` and returns an object that acts like `Script` in all respects, except that it does the checks when it gets instantiated. That way the only difference would be an added underscore (though still less than ideal).

In case of this wrapper, you could even supply nice errors when (for example) the file is missing 😃:
```
func script_instance(resource_path :String) -> Object:
	var script: Script = load(resource_path)
	if script == null:
		return GdUnitAssertImpl.new(self, null).override_failure_message("The script `%s` can't be loaded, does the file exist?" % resource_path).test_fail()
	elif script.can_instance():
		return script.new()
	elif script.reload() == ERR_PARSE_ERROR:
		return GdUnitAssertImpl.new(self, null).override_failure_message("The script `%s` can't be instantiated, possible parse errors!" % resource_path).test_fail()
	else:
		return GdUnitAssertImpl.new(self, null).override_failure_message("The script `%s` can't be instantiated, unknown error!" % resource_path).test_fail()
```

**Comment by Wcubed** [comment]
Here is my attempt with a custom load.

The `_load` function will fail the test case when the resource can't be found.
Calling `new` on the wrapped script will fail the test case when there is an error in the loaded script. For the rest I think it should act exactly like a normal script.

```
extends GdUnitTestSuite

class GdUnitGDScriptWrapper:
	extends GDScript
	
	var _caller: Object
	
	func set_caller(caller: Object):
		_caller = caller
	
	func new():
		if can_instance():
			return .new()
		elif reload() == ERR_PARSE_ERROR:
			return GdUnitAssertImpl.new(_caller, null).override_failure_message("The script `%s` can't be instantiated, possible parse errors!" % resource_path).test_fail()
		else:
			return GdUnitAssertImpl.new(_caller, null).override_failure_message("The script `%s` can't be instantiated, unknown error!" % resource_path).test_fail()


func _load(resource_path: String) -> Object:
	var resource := load(resource_path)
	if resource == null:
		return GdUnitAssertImpl.new(self, null).override_failure_message("The resource `%s` can't be loaded, does the file exist?" % resource_path).test_fail()
	
	if resource.get_class() == "GDScript":
		resource.set_script(GdUnitGDScriptWrapper)
		resource.set_caller(self)
	
	return resource


func test_add() -> void:
	var script = _load("res://error_case/new_script.gd")
	var instance = script.new()
	
	assert_int(instance.add(1,2)).is_equal(3)
```

**Comment by MikeSchulze** [comment]
Good Idea, but it will not solve finally all problems.
e.g. a class with class_name where not need to load will also fail when calling `new`
```
class_name MyClass
extends Node
..
```
```
func test_foo():
   var my_class := MyClass.new()

```  

I'm current researching how to access error reporting from Godot, i had this in my mind some months ago and experimenting with `GdUnitPushErrorHandler`.
But this need time to find a good and reliable solution.

**Comment by Wcubed** [comment]
Good point, I hadn't thought of that. The `ScriptEditorDebugger` GdUnitPushErrorHandler uses looks interesting, I didn't know that one existed 😃 .

**Comment by MikeSchulze** [comment]
@Wcubed sorry but there is current now way to solve this!

This topic is a long term discusion on Godot
https://github.com/godotengine/godot/issues/3516
https://github.com/godotengine/godot/issues/7643

The Godot main developers stubbornly refuse to include a reasonable error handling.

So i close as won't fix

**Comment by nightblade9** [comment]
How do other unit-testing frameworks (e.g. GUT) handle this? 

I know GUT uses a test-scene as the test-runner, but I recall many times, running tests and seeing Godot intercept and break on compilation errors.

Maybe you can look into it or ask for some help? https://github.com/bitwes/Gut

**Comment by MikeSchulze** [comment]
@nightblade9 GUT UI runs allways in debug mode.

**Comment by nightblade9** [comment]
> @nightblade9 GUT UI runs allways in debug mode.

So you're saying, that gdUnit3 is only useful if run in debug mode? :)

**Comment by MikeSchulze** [comment]
@nightblade9 no ;)
I implemented "Run" (without debug) to run tests agains your code like do it in runtime (release mode)
The "Run Debug" is usefull to test and debug in realtime your code. (debug mode)

I'm also not happy that Godot not supports any kind of error handlers to check for errors.
I tryed tp grap errors from the debug console but this is very hacky,

So i suggest to run your tests during developing on Debug mode.
The "run" version should at least run faster than the debug version, but I haven't noticed much difference.

**Comment by nightblade9** [comment]
> So i suggest to run your tests during developing on Debug mode

Yeah, this seems to be the most reliable way to see real errors as errors (and not as passing tests). I refactor code a lot, and that makes things break. 

Thanks for looking into this.
