### ISSUE TITLE
GD-117: gdUnit3 can't find tests if two test classes have the same name

### ISSUE THREAD

**Issue by nightblade9** [MikeSchulze/gdUnit3#117]
**The used Godot version:** 3.3

**OS including version:** Windows 10

**Describe the bug**
Create two test classes with the same name, in different directories. One runs, the other reports errors about supposedly missing tests .

**Steps to Reproduce**

- Create `tests/unit/player_tests.gd` with the method `test_cool_stuff`
- Create `tests/integration/player_tests.gd` with method `test_damage_and_idk`
- Right-click the `tests` directory and pick `Run unit tests`

One set of tests runs, the other doesn't. The output window mentions the error about missing tests.

**Comment by MikeSchulze** [comment]
Thanks for reporting, I will have a look soon.
