### ISSUE TITLE
GD-118: False-negative for tests with float

### ISSUE THREAD

**Issue by toby3d** [MikeSchulze/gdUnit3#118]
**The used Godot version:** v3.4.beta2.official
**OS including version:** Linux 5.12.19-1-MANJARO x86_64 GNU/Linux
**Describe the bug**
![image](https://user-images.githubusercontent.com/5412322/127199560-a15cd77f-f5b6-48e9-98c6-987e06a199d8.png)
**Steps to Reproduce**
* Install gdUnit3 addon
* Create simple method with float value manipulation
* Create test for it with `assert_float().is_equal()`
* Run test

**Minimal reproduction project:** [project.zip](https://github.com/MikeSchulze/gdUnit3/files/6887516/project.zip)

**Comment by MikeSchulze** [comment]
Thanks for reporting.

 v3.4.beta2.official is not officially supported yet, but I will have a look at it.

**Comment by MikeSchulze** [comment]
This is not a real bug this is the nature of floats are stored/calculated.
```
	prints ("%.16f" % 2.2)
	prints ("%.16f" % (6.6/3.0))
```
Results in:
```
2.2000000000000002
2.1999999999999997
```
Godot provides a function to compare float by a **approx** `is_equal_approx`
I will add a better `is_equal` on AssertFloat to handle approximately equal to each other.

**Comment by MikeSchulze** [comment]
Added missing documentation
https://github.com/MikeSchulze/gdUnit3/wiki/GdUnitFloatAssert#is_equal_approx
