### ISSUE TITLE
GD-131: Can't extend base test suite when using `extends <resourc_path>`

### ISSUE THREAD

**Issue by nightblade9** [MikeSchulze/gdUnit3#131]
**The used Godot version:** 3.3.2

**OS including version:** Windows 10

**Describe the bug**
Extending a base test class results in this error: `res://addons/gdunit3/src/ui/parts/InspectorTreeMainPanel.gd:33 - Invalid call. Nonexistent function 'has_meta' in base 'Nil'.`

**Steps to Reproduce**
- Create a base class called `BaseTest.gd` that extends `GdUnitTestSuite`
- Create a test suite `MyTests.gd` with the first line being `extends res://tests/BaseTest.gd`
- Try to run tests in `MyTests`

**WORKAROUND**
Use class names instead of resource_paths to extend existing TestSuites
```
class_name BaseTest
extends GdUnitTestSuite

func test_foo() -> void:
	assert_not_yet_implemented()
```
```
extends  BaseTest

func test_foo2() -> void:
	pass

```

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug, i will have a look soon.

**Comment by MikeSchulze** [comment]
@nightblade9 you have to use `extends <class_name>` instead of `extends <class_path>`

I need deeper investigate why using a class_path on extends runs into this issue

**Comment by nightblade9** [comment]
Do you have an example of how extending classes by name works? I don't use class names in GDscript.

**Comment by MikeSchulze** [comment]
hi @nightblade9 it is already described as a workaround in this issue, see at **WORKAROUND**
