### ISSUE TITLE
The assetlib version still shows `.gitmodules`

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit3#140]
**The used Godot version:**
3.3.3

**OS including version:**
MacOS

**Describe the bug**
![image](https://user-images.githubusercontent.com/371014/131668155-be594f8d-49e0-4b4d-b5c0-c5e3b834f1c2.png)

Checking https://github.com/MikeSchulze/gdUnit3/blob/master/.gitattributes it excluded `/.gitmodules`

**Steps to Reproduce**

Install addon through Godot

**Comment by MikeSchulze** [comment]
It was not part of v1.0.3 it was fixed two day later on master branch.
The fix will be include in v1.0.4
