### ISSUE TITLE
Running test from within Godot 3.3.3 fails

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit3#141]
**The used Godot version:**
3.3.3

**OS including version:**
MacOS

**Describe the bug**

```
Save res://addons/gdUnit3/src/Comparator.gd
Save res://src/fabrik.gd
Save res://test/fabrikTest.gd
Save res://addons/gdUnit3/plugin.gd
- res://addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd:313 - Invalid call. Nonexistent function 'has_meta' in base 'Nil'
```

**Steps to Reproduce**

- Create a test for GD script
- Run the test
- Error occurs

## Shell

Running tests from shell seems OK

```
% ./runtest.sh -a test
```

**Comment by MikeSchulze** [comment]
thanks for reporting.

Can you please add more details.
How you run the test? (inspector, editor, or press the play button)

**Comment by MikeSchulze** [comment]
close as already fixed
