### ISSUE TITLE
GD-142: Configurable TestSuite template

### ISSUE THREAD

**Issue by kreivi** [MikeSchulze/gdUnit3#142]
**Describe the solution you'd like**
I would like to be able to configure template to be used when generating `TestSuite`s so I could add licensing boilerplate suggested by [GNU General Public License v3.0](https://choosealicense.com/licenses/gpl-3.0/) on the generated `TestSuite`s.

**Describe alternatives you've considered**
As alternative solution I've used a custom script template that generates a unit test skeleton script but it would be much quicker to use the generator action of GdUnit3

**Comment by MikeSchulze** [comment]
Good idea ;)

I can add an option to popup the current test suite template to be free editable and save as an custom template.

**Comment by kreivi** [comment]
That's great. Let me know if I can help or if you need more details.

**Comment by MikeSchulze** [comment]
here the first screen shot of the template editor
![image](https://user-images.githubusercontent.com/347037/132122684-7dba9d0e-d116-467b-98c5-bc98d4494179.png)

**Comment by MikeSchulze** [comment]
GdUnit 1.0.4 is out, feel free to play with the template editor

**Comment by kreivi** [comment]
It's working great. Thanks for fast response & implementation.
