### ISSUE TITLE
GD-161: Allow the Command Line Tool to use the in GdUnitRunner.cfg included tests

### ISSUE THREAD

**Issue by critcap** [MikeSchulze/gdUnit3#161]
**Is your feature request related to a problem? Please describe.**
At the moment its not possible to run the test which you specified in the editor, which get saved into the GdUnitRunner.cfg.
This leads to a much slower switch from internal to external editor as you need to retype your test preferences.
Which certainly interrupts the workflow.

**Describe the solution you'd like**
Add a new option for the CLI tool besides the existing ones like e.g. " -d, --default", that runs the tests specified in GdUnitRunner.cfg.

**Describe alternatives you've considered**
The "-d, --default" run options an idea and can be interchanged for better worded ones.

**Comment by MikeSchulze** [comment]
good suggestion, i will add the argument
