### ISSUE TITLE
GD-166: Error raised when spying a script that preloads another script (to use its constants, static functions...)

### ISSUE THREAD

**Issue by turbohz** [MikeSchulze/gdUnit3#166]
_Tried looking for any issue with `load_source_code` and `class_path`_

**The used Godot version:**
Godot 3.3.4

**OS including version:**
Arch Linux

**Describe the bug**
I'm trying to **spy** on a class instance, which references static fields and functions preloaded from another script.

Running the test raises an error, specifically `extract_class_path` returns in this particular case a `PoolStringArray` of 1 element (the script file path), so `class_path[1]` is not set.

`GdScriptParser.gd:load_source_code()`

```gdscript
func load_source_code(script :GDScript, script_path :PoolStringArray) -> PoolStringArray:
	var map := script.get_script_constant_map()
	for key in map.keys():
		var value = map.get(key)
		if value is GDScript:
			var class_path := GdObjects.extract_class_path(value)
			_scanned_inner_classes.append(class_path[1])
(...)
```

> Invalid get index '1' (on base: 'PoolStringArray').

Relevant portion of  `extract_class_path` (in this case, we get no`@subpath`):

`GdObjects.gd:extract_class_path`()

```gdscript
(...)
if clazz is GDScript:
	# if not found we go the expensive way and extract the path form the script by creating an instance
	var arg_list := build_function_default_arguments(clazz, "_init")
	var instance = clazz.callv("new", arg_list)
	var clazz_info := inst2dict(instance)
	GdUnitTools.free_instance(instance)
	clazz_path.append(clazz_info["@path"])
	if clazz_info.has("@subpath"):
		var sub_path :String = clazz_info["@subpath"]
		if not sub_path.empty():
			var sub_paths := sub_path.split("/")
			clazz_path += sub_paths
	return clazz_path
```

**Steps to Reproduce**

See the repro test below.

**Minimal reproduction project:**

I forked this repository and added an example test.

1. clone the forked repo:
   > git clone --recursive -b "issue-repro" https://github.com/turbohz/gdUnit3
1. run the test:
   > ./runtest.sh -a gdUnit3-examples/Issue

**Comment by turbohz** [comment]
Skipping `_scanned_inner_classes.append(class_path[1])` (by checking that `class_path.size() > 1`) seems to do the trick, and tests pass, at least for this simple example.

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug, i will have a look soon.
