### ISSUE TITLE
GD-181: Cannot dismiss debug test/ run test options list in the test inspector

### ISSUE THREAD

**Issue by brunosxs** [MikeSchulze/gdUnit3#181]
**The used Godot version:**
3.3.4

**OS including version:**
Manjaro linux with kernel .14.10-1

**Describe the bug**
![Screenshot_20211114_042635](https://user-images.githubusercontent.com/1557903/141671971-9d520fa7-e513-4ee2-b6f8-8b103114bc00.png)

**Steps to Reproduce**

1- Have any test info on the test inspector
2- Right click to open the options list to Debug/Run test
3- Click anywhere else to try to dismiss the list

**Minimal reproduction project:**

Can be reproduced fairly easily with the demo projects.

**Comment by MikeSchulze** [comment]
Thanks for the report, yes the context menu should disappear when you click anywhere.

**Comment by MikeSchulze** [comment]
fixed ;)
