### ISSUE TITLE
GD-183: Use monospaced font on GdUnit console to prints formatted 

### ISSUE THREAD

**Issue by paulhocker** [MikeSchulze/gdUnit3#183]
The output on the Console is not aligned because it is not using a monospaced font.

Change the console to use a monospaced font.

Looked for option in Godot but did not see any.

Thanks for your consideration.

**Comment by MikeSchulze** [comment]
Hi you mean the GdUnitConsole?

**Comment by paulhocker** [comment]
Yes, it is a very small request. I admit. But if the "passed" text could all be aligned on the right side, it would really help me identify the ones not passing. Too much eye movement right now. I assumed that it might be the font, but maybe all that is needed it to align it better? Again, not a high priority. The tools is awesome, and I have tried all the other ones. This one is fast, integrated well, easy to setup/use and provides great feedback. And the assert library is spot on.

Thanks for your consideration of my small request.

**Comment by MikeSchulze** [comment]
Hi thanks for your feedback, that's good to hear ;)
The GdUnit console is more of a relic ;) and I left it in for completeness.
The GdUnit inspector should give you the better feedback, it also has the advantage of jumping directly to an error.

But yes the font should be monospaced, the prints are already formatted to bring in the right shape.

Best Regards
