### ISSUE TITLE
GD-195: Parameterized test does not call `before_test` for each iteration

### ISSUE THREAD

**Issue by batomow** [MikeSchulze/gdUnit3#195]
Godot 3.4.stable_arch_linux
NVIDIA-SMI 495.44
Driver Version: 495.44
CUDA Version: 11.5
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.0

Im running  a test where I insert 10 items into a dictionary, but the test runs multiple times and reports 20 items, where there should only be 10. Im using 'before_test' which clears the dictionary contents before each test. I've checked that the clear function works properly between different tests. Im unsure if running the same test multiple times is intended behavior and im missing some config but seems to me like a bug. 

![image](https://user-images.githubusercontent.com/15216737/147427603-3a918959-667b-453e-99a9-9077ed59d92a.png)

Test Suit
```
extends GdUnitTestSuite

var hashmap
const cell_size = 48

func before(): 
	hashmap = HashMap.new(cell_size)

func before_test():
	hashmap.clear()

"""Some other tests here ... """	
	
func test_add_and_get_objects(fuzzer := Fuzzers.rangev2(Vector2(-47, -47), Vector2(47, 47))): 
	var nodes = []
	for __ in range(10): 
		var n = {"global_position": fuzzer.next_value()}
		hashmap.add(n)
		nodes.push_back(n)
	var result = hashmap.get_objects(0, 0)
	assert_array(result).is_not_null()
	if is_failure(): return
	assert_array(result).is_not_empty()
	if is_failure(): return
	assert_array(result).has_size(10)
	if is_failure(): return
	assert_array(result).contains(nodes)
	if is_failure(): return

```

Hashmap Class
```
class_name HashMap extends Reference

var cell_size:int
var objects = []
var map = {}

"""Some more code here ... """

func clear(): 
	objects = []
	map = {}
	
func get_objects(x, y):
	var key = "%s-%s" % [x, y]
	if key in map: 
		return map[key]
	return []
```
I can get around this by doing another hashmap.clear() call at the end of the test to clean the data, but this is cumbersome.

**Comment by MikeSchulze** [comment]
Hi thanks for reporting this bug.

The **test_before** should be called before every test run, but is only called once for parameterized tests, which is an error.

If you use parameterized tests (fuzzing), the default iteration is set to **1000**.
This means that your test will be called 1000 times with different fuzzer values.
You can configure the number of iterations by setting the limit with **fuzzer_iterations**.
https://github.com/MikeSchulze/gdUnit3/wiki/Fuzzing#using-fuzzers
