### ISSUE TITLE
GD-197: Multiline test arguments not working

### ISSUE THREAD

**Issue by batomow** [MikeSchulze/gdUnit3#197]
Godot 3.4.stable_arch_linux
NVIDIA-SMI 495.44
Driver Version: 495.44
CUDA Version: 11.5
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.0

Im running 2 tests, in the first one im specifically telling it to use 10 iterations but it only runs once. Im doing a `print(hasmap.map.size())` to see how many times this function runs and only outputs size 0 once. 
In the second one im telling it to use 1 iteration and it works fine as per the feedback from this https://github.com/MikeSchulze/gdUnit3/issues/195 .
```
##first test
func test_add_and_remove(
	fuzzer := Fuzzers.rangev2(Vector2(-47, -47), Vector2(47, 47)),
	nfuzzer := Fuzzers.rangei(0, 9), 
	fuzzer_iterations = 10
	): 
	print(hashmap.map.size())
	var nodes = []
	var hashes = []
	for __ in range(10): 
		var n = {"global_position": fuzzer.next_value()}
		hashmap.add(n)
		nodes.push_back(n)
		hashes.push_back(hashmap.get_hash(n))
	var node = nodes[nfuzzer.next_value()]
	nodes.erase(node)
	hashmap.remove(node)
	var result = hashmap.get_objects(0, 0)
	assert_array(result).is_not_null()
	if is_failure(): return
	assert_array(result).is_not_empty()
	if is_failure(): return
	assert_array(result).has_size(9)
	if is_failure(): return
	assert_array(result).contains_exactly(nodes)
	if is_failure(): return
```
```
##second test 
func test_add_and_get_objects(
	fuzzer := Fuzzers.rangev2(Vector2(-47, -47), Vector2(47, 47)), 
	fuzzer_iterations = 1
	): 
	var nodes = []
	for __ in range(10): 
		var n = {"global_position": fuzzer.next_value()}
		hashmap.add(n)
		nodes.push_back(n)
	var result = hashmap.get_objects(0, 0)
	assert_array(result).is_not_null()
	if is_failure(): return
	assert_array(result).is_not_empty()
	if is_failure(): return
	assert_array(result).has_size(10)
	if is_failure(): return
	assert_array(result).contains(nodes)
	if is_failure(): return
```
![image](https://user-images.githubusercontent.com/15216737/147513218-3d87b589-686d-48ba-9279-11fb387a6d1b.png)

Im expecting the first test to fail because im telling it to run 10 iterations without clearing the hashmap contents but it passes, confirming that it only runs once. 
![image](https://user-images.githubusercontent.com/15216737/147513423-2f7c9086-a556-4258-a2ad-d90c7df376af.png)

**Workaround**
Use a single line function, including arguments. Multiline formatted function definition has current problems to be parsed.
```
func test_add_and_get_objects(fuzzer := Fuzzers.rangev2(Vector2(-47, -47), Vector2(47, 47)),  fuzzer_iterations = 1):
   ....
````

**Comment by MikeSchulze** [comment]
Hi that sounds strange, i have testcoverage to verify the test is called by the configured amount of iterations ;(
I will verify and give you feedback.

**Comment by batomow** [comment]
> Hi that sounds strange, i have testcoverage to verify the test is called by the configured amount of iterations ;( I will verify and give you feedback.

Thanks chief. Ill try and take a look at the source code to see if i can find the problem myself.

**Comment by MikeSchulze** [comment]
I found the problem.
The test parser has problems with multiline function arguments.
As workaround you should format the test function to one liner.
```
func test_add_and_remove(fuzzer := Fuzzers.rangev2(Vector2(-47, -47), Vector2(47, 47)),nfuzzer := Fuzzers.rangei(0, 9), fuzzer_iterations = 10): 
		prints("test_add_and_remove", fuzzer.iteration_index())
```
