### ISSUE TITLE
GD-202: Always use godots standard theme for update panel

### ISSUE THREAD

**Issue by BenHerbst** [MikeSchulze/gdUnit3#202]
**Is your feature request related to a problem? Please describe.**
When the nice update panel comes up, it has the theme of my games theme, but it would be better if it is the editor theme, as games often have textured themes etc. and my game theme only uses some components like buttons etc. and then in the update panel the other components are godot standard and it is a mix and it would be easier to set it to godots standard blue theme.

**Describe the solution you'd like**
To use the Godots standard blue theme in update panels.

**Describe alternatives you've considered**
Update button in the dock.

**Additional context**
None.

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue, sounds me like a bug.

The update panel should have the current editor theme and not project related theme.

**Comment by BenHerbst** [comment]
How should I make a screenshot, when I already  updated? I mean: The update panel only shows up when there is an update.

**Comment by BenHerbst** [comment]
![image](https://user-images.githubusercontent.com/83538916/147754607-dc980023-e7fa-4254-b77c-f1046464a2c2.png)
The GdUnitTools panel doesn't has this issue. Maybe check difference in your code?

**Comment by MikeSchulze** [comment]
ok i will have a look to reproduce tomorrow.
You can force the update by delete plugin and reinstall from AssetLib

**Comment by BenHerbst** [comment]
![image](https://user-images.githubusercontent.com/83538916/147755259-a1d7d1cc-1296-42c5-8b1d-537fe2310494.png)
I created a new project and created a new theme, so it looks like the Godot 2 theme.

**Comment by BenHerbst** [comment]
[bugtest.zip](https://github.com/MikeSchulze/gdUnit3/files/7793071/bugtest.zip)
