### ISSUE TITLE
Ship with Godot

### ISSUE THREAD

**Issue by BenHerbst** [MikeSchulze/gdUnit3#203]
**Is your feature request related to a problem? Please describe.**
This plugin is so great and well implemented, that it would be nice to be shipped with godot, so users don't have to install it as plugin and they can easily use the best plugin for gdscript and later C# when it is fully supported.

**Describe the solution you'd like**
Build it into the engine.

**Describe alternatives you've considered**
Still be a plugin.

**Additional context**
None.

**Comment by MikeSchulze** [comment]
Thank you very much for the nice feedback. 

To build in the plugin in Godot is not in my hands , feel free to request this directly to the Godot team.
It will all have to be rewritten in cpp and will take a lot of effort.
I am currently working on C# support and the next step will be to replace the gdScript code with gdNative.
This will open up more possibilities that are not possible with GdScript (e.g. exception handling).

At least using it as a plugin is not a big deal. To make it more user friendly there is the automatic update process to simplify the nerfy plugin reinstall.
