### ISSUE TITLE
Testing asserts

### ISSUE THREAD

**Issue by batomow** [MikeSchulze/gdUnit3#204]
Godot 3.4.stable_arch_linux
NVIDIA-SMI 495.44
Driver Version: 495.44
CUDA Version: 11.5
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.0

Im trying to test that my function runs an assertion correctly. But the test fails. 
```
##Test suit
func test_f__init_assert_invalid_cellsize():
	var failure_message = "cellsize has to be greater than 0"
	assert_that(HashMap.new(0)).has_failure_message(failure_message)
```

```
##Code
func _init(c).():
	assert(c > 0, "cellsize has to be greater than 0")
	cellsize = c
```

![image](https://user-images.githubusercontent.com/15216737/147814761-fc7f9db9-2ce5-479f-b9fa-21e3d6bf30c0.png)

The same happens with other assertions that are not in the _init() function.

**Comment by MikeSchulze** [comment]
Hi @batomow

A Godot assert just stop on debug if the condition is false or kills the program at runtime.
Godot asserts are not catched by GdUnit3 this is not current possible.
At least all internal errors can't be catched there is no error handler or such thinks to act on.

The used assert_that(<>).has_failure_message(<expected>) is not related to Godot asserts.
This function is used to finally check if the reported assert failure equal expected failure message.
I used this mainly for the assert selfcheck the expected assert failure messages, to verify if the condition mit einer bestimmten message fails.

Like this:
```
	assert_bool(null, GdUnitAssert.EXPECT_FAIL).is_false() \
		.has_failure_message("Expecting: 'False' but is 'Null'")
```

So it is not a bug therefore I close as clearified.

**Comment by batomow** [comment]
So how would you go about testing this peace of code then?..
```
func _init(c).():
	assert(c > 0, "cellsize has to be greater than 0") #this line i want to test
	cellsize = c
```

**Comment by MikeSchulze** [comment]
Godot asserts are not testable because there is now way to catch them.
Godot asserts are designed to use for prevent invaid programming state and usally helps to find bugs durung run you program in debug mode. [asserts](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#assert-keyword)

You should not change the `_init` function signature to return an other type! The signature should be `-> void:` 
There is also no need to call the parent class constructor for standard constructors.
[See here](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#class-constructor)

The best practice would be to add an warning if the argument has an unexpected value and fallback to a default value.
```
class_name HashMap
extends Resource

const DEFAULT_CAPACITY = 10
var _capacity :int

# constructs the hashmap with a default capacity of 10 if no argument given
func _init(capacity := DEFAULT_CAPACITY):
	if capacity <= 0:
		push_warning("Invalid inital capacity %s. Fallback to %s" % [capacity, DEFAULT_CAPACITY])
		_capacity = DEFAULT_CAPACITY
	else:
		_capacity = capacity
```
and test it by
```
# GdUnit generated TestSuite
#warning-ignore-all:unused_argument
#warning-ignore-all:return_value_discarded
class_name HashMapTest
extends GdUnitTestSuite

# TestSuite generated from
const __source = 'res://HashMap.gd'

func test_construct_default_capacity() -> void:
	var map = HashMap.new()
	assert_int(map._capacity).is_equal(HashMap.DEFAULT_CAPACITY)

func test_construct_custom_capacity() -> void:
	var map = HashMap.new(20)
	assert_int(map._capacity).is_equal(20)

func test_construct_by_invalid_capacity() -> void:
	var map = HashMap.new(-20)
	assert_int(map._capacity).is_equal(HashMap.DEFAULT_CAPACITY)
```

**Comment by batomow** [comment]
This was extremely helpful.

**Comment by MikeSchulze** [comment]
This is part of the test suite template and allows you to reuse it on you tests. e.g. for loading the source.
Take a look at GdUnit3 configuration dialog at templates.
![image](https://user-images.githubusercontent.com/347037/147872288-6ba851c1-ab6a-41cd-a8bc-0052ae3956da.png)

The full description of supported tags can be read by pressing the "Supported Tags" button,
