### ISSUE TITLE
GD-207: Using nested fuzzer as type-safe arguments results in `Null` value 

### ISSUE THREAD

**Issue by batomow** [MikeSchulze/gdUnit3#207]
```
var method_definitions = [
	TU.fun("_init", TYPE_NIL, [
		TU.arg("cellsize", TYPE_INT)
	]),
	TU.fun("clear", TYPE_NIL),
	TU.fun("get_hash", TYPE_DICTIONARY, [
		TU.arg("position", TYPE_VECTOR2)
	]),
	TU.fun("add_object",TYPE_NIL, [
		TU.arg("object", TYPE_NIL)
	]), 
]

class MethodDefinitionFuzzer extends Fuzzer: 
	var data: Array

	func _init(definitions:Array).():
		assert(definitions)
		data = definitions

	func next_value()->Dictionary: 
		assert(not data.empty())
		return data[(_iteration_index-1)%data.size()]

func test_i_has_methods(fuzzer := MethodDefinitionFuzzer.new(method_definitions), fuzzer_iterations=1): 
	assert_that(fuzzer).is_not_null()
```
![image](https://user-images.githubusercontent.com/15216737/147889890-43553750-428d-486a-9abb-10e4ae476ddb.png)

**Workaround**

Use untyped arguments.
e.g.
`func test_i_has_methods(fuzzer = MethodDefinitionFuzzer.new(method_definitions), fuzzer_iterations=1): `
Or convert nested class to top level class

**Comment by MikeSchulze** [comment]
Hi thanks for reporting this issue.

I have seen this issue some time ago but i forget to create a bug ticket :)

You can workaround by
`func test_i_has_methods(fuzzer = MethodDefinitionFuzzer.new(method_definitions), fuzzer_iterations=1): `

**Comment by MikeSchulze** [comment]
Hi @batomow after some research i come to the concludtion this is a Godot related bug.

This problem only occurs when the custom fuzzer is a nested class.
When converting the nested class to a top level class the typed argument is working.

I tested it by 
```
class NestedFuzzer extends Fuzzer:
	
	func _init():
		pass
	
	func next_value()->Dictionary: 
		return {}

func test_create_nested_fuzzer_do_fail():
	var fuzzer_func := "fuzzer:=NestedFuzzer.new()"
	var fuzzer := FuzzerTool.create_fuzzer(self.get_script(), fuzzer_func)
	assert_that(fuzzer).is_not_null()
	assert_that(fuzzer is Fuzzer).is_true()
	# the fuzzer is not typed as NestedFuzzer seams be a Godot bug
	assert_bool(fuzzer is NestedFuzzer).is_false()

func test_create_external_fuzzer():
	var fuzzer_func := "fuzzer:=TestExternalFuzzer.new()"
	var fuzzer := FuzzerTool.create_fuzzer(self.get_script(), fuzzer_func)
	assert_that(fuzzer).is_not_null()
	assert_that(fuzzer is Fuzzer).is_true()
	assert_bool(fuzzer is TestExternalFuzzer).is_true()
```
And you can see the nested fuzzer is not a type of NestedFuzzer.

**Comment by MikeSchulze** [comment]
Closed as Godot related bug.
Added workaround to the bug description.
