### ISSUE TITLE
GD-209: Support Same Test Attributes as existing c# Test framework (nunit/xunit)

### ISSUE THREAD

**Issue by GeorgeS2019** [MikeSchulze/gdUnit3#209]
**Is your feature request related to a problem? Please describe.**

Look very promising. 
Feedback for encouraging fast adoption for new users.
**Describe the solution you'd like**

Same Test Attributes and SAME EXPERIENCE as existing test framework. This will attract more users to use as there is no re-learning. Also, they will know what have been implemented and how their behaviors should be. This will speed up the development as new users know exactly what to look and what to expect by applying the same experience from prior experience

**Describe alternatives you've considered**

Very promising, no alternative needed.

**Additional context**

**Comment by MikeSchulze** [comment]
Thank you for the kind feedback 👍 

If you correct understand you request to have the same test attributes as GdUnit3 gd-script tests supports?
This is already the plan.
The GdUnit3 c# API would be the same like the gd API, plus some improvements ;)

Or you mean to support test attributes like nunit/xunit?

**Comment by GeorgeS2019** [comment]
>support test attributes like nunit/xunit? 

YES

**Comment by MikeSchulze** [comment]
Hi @GeorgeS2019 i take a deeper look into the xUnit and nUnit API and the attributes are different.

| API | test-suite | setup/teardown | test-case |
|---|---|---|---|
|nUnit| [TestFixture] | [SetUp], [TearDown] |  [Test], [TestCase], .. |
|xUnit| -- | -- | [Fact] |
|gdUnit|  [TestSuite] |  [Before], [After], [BeforeTest], [AfterTest] |  [TestCase] |


xUnit as no attributes for test-suite and setup/teardown methods.

There is no common pattern i found to apply to GdUnit.

**Comment by MikeSchulze** [comment]
Please create a more described feature request for test attributes you miss on GdUnit3
