### ISSUE TITLE
GD-211: Use default font size for all GdUnit3 components

### ISSUE THREAD

**Issue by microaeris** [MikeSchulze/gdUnit3#211]
**Is your feature request related to a problem? Please describe.**
The output text is very small. It renders particularly small on my 4k display.

**Environment**
Godot version you used: 3.3.3
OS/System: macOS Monterey version 12.0.1
Screen resolution: 3840 × 2160

**Describe the solution you'd like**
Add configurable font size, or use editor's font size by default 

**Additional context**
Example screenshot:
![Screenshot](https://media.discordapp.net/attachments/342056330523049988/932722613329985646/Screen_Shot_2022-01-17_at_11.44.38_AM.png)
![Screenshot 2](https://media.discordapp.net/attachments/93018484564303872/932726900319744050/Screen_Shot_2022-01-17_at_12.02.47_PM.png)

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.

It looks very strange, some UI glitches ;(

Can you please add some more infos:
- the Godot version you used?
- the OS/System
- the used screen resolution

**Comment by microaeris** [comment]
Thanks for all of your help so far!

- the Godot version you used? 3.3.3
- the OS/System. macOS Monterey version 12.0.1
- the used screen resolution? 3840 × 2160
