### ISSUE TITLE
GD-215: gdUnitConsole not highlighting the correct diff on failed string assert

### ISSUE THREAD

**Issue by Zovix** [MikeSchulze/gdUnit3#215]
**The used Godot version:**
3.4.2.stable

**OS including version:**
Windows 11 - 21H2
Resolution: 2560x1440
Scale: 110%

**Describe the bug**
gdUnitConsole is highlighting the wrong character on a failed assert_str().is_equal()

_The GdUnit tab is correctly highlighting the failed assertion character._

**Steps to Reproduce**

1. Create a simple test script with an assert_str that will fail.
2. View report in gdUnitConsole

`
class_name NewTest
extends GdUnitTestSuite

func test_test() -> void:
	assert_str("test").is_equal("test1")
`

**gdUnitConsole**
![image](https://user-images.githubusercontent.com/590152/150668389-0a550a84-5ae0-4c52-9f5f-9abc828c3b91.png)

**GdUnit Tab showing correct highlighting**
![image](https://user-images.githubusercontent.com/590152/150668424-c8ece413-2364-4d95-9975-e6e6d63f4d1c.png)

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.

Same here i'm not able to reproduce.

Can you please provide me the used screen resulution and editor settings
![image](https://user-images.githubusercontent.com/347037/150671908-38b8992e-d0e6-410c-a88f-40e3e9f0fdbb.png)

**Comment by MikeSchulze** [comment]
After experimenting with different scale options, I was able to reproduce it
![image](https://user-images.githubusercontent.com/347037/150672009-c567186f-aa72-4e09-bb82-a9981faf0d5c.png)

**Comment by Zovix** [comment]
Here are my current settings.

**Godot**:
![image](https://user-images.githubusercontent.com/590152/150683467-186d33e0-d662-4cda-ad5d-bc5f1e9ed296.png)

**Windows**:
Resolution: 2560x1440
Scale: 110%
