### ISSUE TITLE
[Master] Request for nonexistent project setting: gdunit/report/error_notification

### ISSUE THREAD

**Issue by afonsolage** [MikeSchulze/gdUnit3#24]
**The used Godot version:**
3.3.rc6

**OS including version:**
Ubuntu 20.04 x64 x11 GTX 1650M (proprietary drives)

**Describe the bug**
I just cloned the master and copied `gdUnit3` and `GdCommons` to `/addons` folders. When I started godot on my existing project, the following error shows up:
`Request for nonexistent project setting: gdunit/report/error_notification.`

When testing on a new clean project, there are two more erros:
```
 Request for nonexistent project setting: gdunit/report/error_notification.
 Couldn't create an ENet multiplayer server.
 modules/gdscript/gdscript_functions.cpp:803 - Can't establish server, error code: 20
```

**Steps to Reproduce**
1. Open the test project
2. See error `Request for nonexistent project setting: gdunit/report/error_notification.`

**Minimal reproduction project:**
[test_project.zip](https://github.com/MikeSchulze/gdUnit3/files/6215685/test_project.zip)

**Comment by afonsolage** [comment]
Additional info:
If I set `Gdunit/Report/Error Notification` to `On`, on the next startup of godot, the error won't should, but the property gets set to `Off` again and on the next time Godot is started, the error will show again.

**Comment by MikeSchulze** [comment]
Hi @afonsolage thanks for reporting this issue.

The error 'Request for nonexistent project setting: gdunit/report/error_notification.' can still be ignored 
The property to enable push error reports is currently a prototype and not production ready.

I will remove the error notification in the next release ;)

The second error is more a problem.
If you able to run any test or if the GdUnitInspector empty?
If the error also occurs when you restart godot?

**Comment by afonsolage** [comment]
Actually, no.

I created a dummy scene `Node.tscn` and attached a `Node.gd` to it, as follows:

```gdscript
extends Node


func _ready():
	pass # Replace with function body.


func dummy() -> String:
	return "boo"

```

Then created a new test function using `Right Click -> Create Test`. It failed because the `Node.gd` wasn't on root folder (`res://Node.gd`), but that's another problem, I'll open another issue for that.

After creating a folder, named `scripts` and placing the `Node.gd` inside it, the `Create Test` worked fine, as follow:
```gdscript
# GdUnit generated TestSuite
class_name NodeTest
extends GdUnitTestSuite

# TestSuite generated from
const __source = 'res://scripts/Node.gd'

func test_dummy():
	assert_not_yet_implemented()

```

But when I tried to run the tests (either by using context menu or using the GdUnit panel), only the following message is printed:
`Save test script: [GDScript:19022] res://scripts/test/NodeTest.gd`. No visual changes on GdUnit panel. Even after restart, it didn't worked.

Here is the updated project:
[test_project_updated.zip](https://github.com/MikeSchulze/gdUnit3/files/6215738/test_project_updated.zip)

**Comment by afonsolage** [comment]
After more tests, I think the error was mine, don't know why, but it isn't happening anymore :confused: 

1. Created a brand new project;
2. Added `addons` folder from GdUnit3 repo;
3. Started Godot, enabled plugin;
4. Pressed run tests and it run (even tho there are no tests);

:thinking:

**Comment by MikeSchulze** [comment]
OK, i will checkout Godot 3.3.rc6 for reproduce.
My problem is i don't have a environment Ubuntu to test.

- so current state is you have no errors in the console?
- if you run a testsuite no update is happen on the inspector?

**Comment by afonsolage** [comment]
In short:
* On my existing project, I still got the `Request for nonexistent project setting: gdunit/report/error_notification.` error message when godot starts up, but it doesn't don't causes any issue;

* On brand new test project, I won't get that ENet error enymore, so I think this issue can track the above mentioned error, so I can't reproduce it anymore.

**Comment by MikeSchulze** [comment]
Sounds strange ;)
But see you any progress in the inspector? 
- list of executed testsuites with state success or fail

**Comment by afonsolage** [comment]
No problem, here it goes again, but this time, I'll register each step:

1. Created a brand new project, named `test_project`
2. Opened up Godot;
3. Copied `addons` folder from `GdUnit3` repository and placed on `test_project` folder
4. Enabled `GdUnit3` on Godot

The following output appear:
```
Godot Engine v3.3.rc6.official (c) 2007-2021 Juan Linietsky, Ariel Manzur & Godot Contributors.
 Request for nonexistent project setting: gdunit/report/error_notification.
 Couldn't create an ENet multiplayer server.
 modules/gdscript/gdscript_functions.cpp:803 - Can't establish server, error code: 20
Loading GdUnit3 Plugin success
```
5. Clicked on GdUnit panel tab and hit `Run Tests`, the button grayed out and nothing happens:
![image](https://user-images.githubusercontent.com/1176452/112725022-c6003980-8ef4-11eb-9640-3a4f02a6e79b.png)
6. Clicked on "Stop" button. The following error shows up:
```
 res://addons/gdUnit3/src/ui/GdUnitInspector.gd:381 - Invalid type in function '_gdUnit_stop' in base 'Panel (GdUnitInspector.gd)'. Cannot convert argument 1 from Nil to in
```
7. Right clicked on GdUnit folder, but the run/debug tests are disabled:
![image](https://user-images.githubusercontent.com/1176452/112725074-08c21180-8ef5-11eb-922a-46f50cf82c0a.png)
8. Restarted Godot
9. When Godot shows up, the same output as step 4 appears:
```
Godot Engine v3.3.rc6.official (c) 2007-2021 Juan Linietsky, Ariel Manzur & Godot Contributors.
 Request for nonexistent project setting: gdunit/report/error_notification.
 Couldn't create an ENet multiplayer server.
 modules/gdscript/gdscript_functions.cpp:803 - Can't establish server, error code: 20
Loading GdUnit3 Plugin success
```
10. Tried again running tests, but the same results as steps 5 and step 6 happened
11. Closed godot and zipped the project:
[teste_project.zip](https://github.com/MikeSchulze/gdUnit3/files/6215876/teste_project.zip)
12. Started Godot again and the same output as 4 and 9 appears
13. Create a new `Node` scene, saved it as `Node.tscn`
14. Tried again to run tests, same thing as 5 and 6 happens.

**Comment by afonsolage** [comment]
Nvm. I figured it out! :laughing: 

I had already another instance of Godot editor running with the `GdUnit3` plugin active. So `Network.gd` is biding the same port.

I think this can be fixed by either adding the networking port  to be configurable or assing a random port whenever it started.

The downside of this issue is we can't have two Godot Editor instances running at the same time, with the plugin enabled.

**Comment by MikeSchulze** [comment]
Ah now come light in the problem ;)

Sounds finally it is a running multiple Godot instances at same time.
Yes this is currently a problem of hard coded server port.

I will figure out to manage this by using using an random free port for each instance or simply adding a new setting to manage the port.

So running GdUnit3 on a single Godot instance works as described in the tutorial?

**Comment by afonsolage** [comment]
Yes. Everything is fine when you don't forget another instance of godot running :sweat_smile:

**Comment by MikeSchulze** [comment]
Thats good news ;) 

I will create a new issue to support multiple running godot instances.
This issue will be handle now only the settings issue.

Thanks for you hard testing :)

**Comment by MikeSchulze** [comment]
merged into master
