### ISSUE TITLE
GD-246: Add error handler to catch `push_error` and script errors at test execution.

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit3#246]
Currently GdUnit is not able to handle `push_error` or script errors at runtime (not debug mode), such tests end with success but should fail.
This is a major problem with the Godot API, which simply ignores such errors and continues execution. 

Example Test-suite
```
# GdUnit generated TestSuite
#warning-ignore-all:unused_argument
#warning-ignore-all:return_value_discarded
class_name TestTest
extends GdUnitTestSuite

# TestSuite generated from
const __source = 'res://test.gd'


func test_with_script_errors() -> void:
	# this test should fail here because the Resource has no function `foo`
	Reference.new().foo()
	assert_str("abc").is_empty()

func test_with_push_errors() -> void:
	# this test should fail here because a `push_error` is used
	push_error("Test error push notification")
	assert_str("abc").is_empty()
````
When run this suite with "run" one test is passed but should be failed
![image](https://user-images.githubusercontent.com/347037/167472542-f2776c6f-b311-48da-ae44-920d4d057a19.png)
The Godot.log shows
```
SCRIPT ERROR: TestTest.test_with_script_errors: Invalid call. Nonexistent function 'foo' in base 'Reference'.
          At: res://test_test/test_test.gd:13
ERROR: call: Test error push notification
   At: modules/gdscript/gdscript_functions.cpp:803
```

**Describe the solution you'd like**
GdUnit should report script errors and let test fail.
![image](https://user-images.githubusercontent.com/347037/167473926-434a6123-d84f-4133-bad6-0b7df5c03401.png)

And optional/configuable failing for `push_error`.

**Describe alternatives you've considered**
There is no API on Godot at the moment to catch such errors.

**Comment by nightblade9** [comment]
Thanks for creating this. The optional flag is really important for me; I have lots of validation in my game code that my tests break (e.g. look for a player and find zero, or two) that call `push_error`. I would need this off for all my tests.

**Comment by MikeSchulze** [comment]
> Thanks for creating this. The optional flag is really important for me; I have lots of validation in my game code that my tests break (e.g. look for a player and find zero, or two) that call `push_error`. I would need this off for all my tests.

Yes, that's the reason why I wanted to make it optional ;)

**Comment by MikeSchulze** [comment]
BTW you can join the GdUnit3 Discord server for direct comunication ;)

**Comment by nightblade9** [comment]
I'll keep that in mind for next time, thanks!
