### ISSUE TITLE
Verify that method isnt called with arguments on Mock

### ISSUE THREAD

**Issue by Matthew-Underwood** [MikeSchulze/gdUnit3#255]
When testing expectations on mocks sometimes I find that I need to ensure that a method on a mock hasnt been called with a certian set of arguments in order for the unit test to pass. For example I need to ensure that a Vector2(5, 5) hasnt been passed in to the add_point method of Godots native AStar native object. 

I tried to set the times to zero to see if it would pass, but no luck. eg `verify(mockObject, 0).add_point(Vector2(5, 5))`

The solution would be either to verify that a method was called zero times like in the example above by either setting the times to zero or having a new method such as verify_not_called.

Major mocking frameworks such as PHP's Mockery supports this thing and its integral to unit testing.

**Comment by MikeSchulze** [comment]
Hi i guess you using the API wrong.

The `AStar` expects on function `add_point` two arguments
`void add_point(id: int, position: Vector3, weight_scale: float = 1.0)`

Your test should be
```
func test_mock():
	var m := mock(AStar) as AStar
	verify_no_interactions(m)
	
	# success is never called with args (0, Vector3(5, 5, 5))
	verify(m, 0).add_point(0, Vector3(5, 5, 5))
	
	# now call it
	m.add_point(0, Vector3(5, 5, 5))
	# will fail
	verify(m, 0).add_point(0, Vector3(5, 5, 5))
```

**Comment by Matthew-Underwood** [comment]
Yeah it was a fault with my implementation. Like you said the times argument set to zero works fine. My problem was that I was matching against the wrong type when performing argument expectations. I was using `any_int()` rather than `any_float()`. Thanks

**Comment by MikeSchulze** [comment]
I'm glad I could help and hope you enjoy.
Ideas to improve the API are always welcome
