### ISSUE TITLE
GD-256: Build a mock inherits with the wrong class if the filename matches an existing class

### ISSUE THREAD

**Issue by Matthew-Underwood** [MikeSchulze/gdUnit3#256]
Hello there

For my class names I prefix them with the vendor name and the module name that they belong to e.g. a class called Ball in the pathing module would be `class_name Munderwood_Pathing_Ball`. The name of the class file will be called `ball.gd`. This means there is no chance of class name clashes when introducing modules that may contain other `ball.gd` classes in a Godot project. This is a widely used practise across many languages testing frameworks. The problem with this in the context of GdUnit is that when creating the mock of the class it uses the name of the file from the class rather than the class name itself. I ran into a case where it created a Mock of Godot native class `World` because the class I wanted to mock was called `class_name Munderwood_Pathing_World` with the file name of `world.gd`.

I implemented a solution where it maps the namespace prefix value to a file path which contains the classes that contain that namespace  e.g. namespace prefix `Munderwood_Pathing` would belong to all the classes in the path `addons/pathing/src/`. 

I would prefer to not have my hack in place and instead make this a formal feature as a option for people who use namespace prefixes in their class naming convention like I do. 

## Steps to Reproduce
* create a class and named  it `world.gd` and use a different class_name  e.g. `class_name <Munderwood_Pathing_World>`
```
extends Node
class_name Munderwood_Pathing_World

func foo() -> String: 
	return "test"
```
* create a test suite and mock this class by resource_path
```
# GdUnit generated TestSuite
#warning-ignore-all:unused_argument
#warning-ignore-all:return_value_discarded
class_name MunderwoodPathingWorldTest
extends GdUnitTestSuite

# TestSuite generated from
const __source = 'res://GD-256/world.gd'

func test_mock_by_path() -> void:
	var m = mock(__source)
	assert_str(var2str(m)).contains("extends Munderwood_Pathing_World")

func test_mock_by_class() -> void:
	var m = mock(Munderwood_Pathing_World)
	assert_str(var2str(m)).contains("extends Munderwood_Pathing_World")
```
The test shows the mock is extending from `World` but should extend from `MunderwoodPathingWorldTest`
![image](https://user-images.githubusercontent.com/347037/170441916-d386963d-4721-4c30-9ebb-ed28d23a4898.png)

## AC:
* Use the `class_name` if exists to build a mock/spy

**Comment by MikeSchulze** [comment]
Hi @Matthew-Underwood 

Thanks for reporting this issue.
Sounds like a design error from my mock implementation to me ;)
I had in mind that I was using the class_name and not the filename, I'll have to check that.

I will create a test later today to verify the issue you describe and provide a fix.

**Comment by Matthew-Underwood** [comment]
Thanks, I was thinking about it last night and realized that the fix wouldn't be the feature that I stated earlier but in fact that it needs to use the class name rather than the file name like you said.
