### ISSUE TITLE
Add a option to generate Static Typed GDScript tests

### ISSUE THREAD

**Issue by afonsolage** [MikeSchulze/gdUnit3#26]
**Is your feature request related to a problem? Please describe.**
When a new test is generated, it generates the default dynamic GDScript syntax, since I use Static Typed GDScript, I need to convert it, which isn't a big deal, I just need to add `-> void:` at the end of the function.

Since the number of Static Typed GDScript is increasing, due the Godot 4.0 performance improvements, it would be a good idea to have an option to generate the code using the Static Tyuped GDScript

**Describe the solution you'd like**
Add a configuration option to generated new code using Static Typed GDScript syntax.

**Describe alternatives you've considered**
Just keep adding it manually. It isn't a big deal also, just a minor QoL

**Additional context**
N/A.

**Comment by MikeSchulze** [comment]
For clarification you mean 'create Test' should create a typed test case right?

like this
```
# GdUnit generated TestSuite
class_name ExampleTest
extends GdUnitTestSuite

# TestSuite generated from
const __source = 'res://foo/src/core/Example.gd'

func foo() -> void:
	# remove this line and complete your test
	assert_not_yet_implemented()
````
