### ISSUE TITLE
GD-260: GdUnit3 doesn't fail on script errors during test run

### ISSUE THREAD

**Issue by nightblade9** [MikeSchulze/gdUnit3#260]
**The used Godot version:** 3.4.4 official
**OS including version:** Windows 10

**Describe the bug**
This test passes in debug and release mode. It should fail in at least debug mode.

```
extends GdUnitTestSuite

func test_kaboom():
  var x = 0.0
  var z = test.haha() # also: var z = 1.0 / x
  assert_bool(true).is_true()
```

**Steps to Reproduce**
- Install Godot 3.4.4 official (non-Mono) version on Windows
- Create a new project
- Download gdUnit3 from the asset lib and activate it
- When the gdUnit3 upgrade popup appears, pick upgrade
- Restart the current Godot project
- Verify that Project > Settings, Gdunit 3 > Report > Script Error is `[x] On`
- Create a test file like the one indicated above
- Run it in debug or release mode

As mentioned on Discord: it seems to work for you with Godot v3.3.3 (mono), I don't know if that's significant. 

```
# godot.log

Godot Engine v3.4.4.stable.official.419e713a2 - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
OpenGL ES Batching: ON

Unicode error: invalid skip
connect_to_host 127.0.0.1 31002 0
TCP Client: Connected to Server: 83084
SCRIPT ERROR: Invalid call. Nonexistent function 'haha' in base 'float'.
    at: test_kaboom (res://tests/test_cases/GDUnitTests.gd:9) - Invalid call. Nonexistent function 'haha' in base 'float'.
```

**Comment by MikeSchulze** [comment]
Hi @nightblade9 

I was able to reproduce the problem today during a test period.
I have found the root cause and will provide a solution. 

Thanks for reporting this bug

**Comment by MikeSchulze** [comment]
> Great, let me know when there's a new update available, I can try and test it on that same machine again.

You can install manually if you want.
I need some time to complete the v2.2.0 release, it needs also to update the vsc extension to be compatible to v2.2.0.
