### ISSUE TITLE
GD-262: TestSuites without namespace are not found/executed

### ISSUE THREAD

**Issue by musicm122** [MikeSchulze/gdUnit3#262]
$ dotnet --version
6.0.300

Visual Studio Code Version: 1.67.2

**The used Godot version:**
godot v3.4.4 stable mono official version

**OS including version:**
Edition	Windows 10 Pro
Version	21H2
Installed on	‎3/‎17/‎2021
OS build	19044.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

Processor	AMD Ryzen 9 3900X 12-Core Processor               3.79 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor

NVidia GeForce RTX 2080 SUPER
GeForce Game Ready Driver
Version: 512.95 

**Describe the bug**

After installing gdUnit3, Tests do not appear and "generate test" tooling does not create new tests.

**Steps to Reproduce**

## Test not showing 
1. Perform the installation via these steps (using 2.2.0 .Net 6 and Lang version 10) .
https://mikeschulze.github.io/gdUnit3/first_steps/install/

![godot_runner](https://user-images.githubusercontent.com/725185/170834795-32f974b3-3cc8-492a-9ebf-00e264e82600.png)

## Generate Test fails
1. Open vscode to cs file to be tested.
2. Using cursor select method to test in cs file.
3. Right click 
4. Select "Create GdUnit Test"

Expected : New file to be generated

Actual Output: 
```
Generate Test Case ...
Can't generate test case! 100 null
```

![cant_generate_test_case](https://user-images.githubusercontent.com/725185/170834792-ff4612e0-acc1-4854-ace4-b186ecbdd692.png)

**Minimal reproduction project:**

[GDTest_Example.zip](https://github.com/MikeSchulze/gdUnit3/files/8791504/GDTest_Example.zip)

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug.

I'm able to reproduce it with the attached example.
I will take a look deeper tomorrow and provide a fix soon as possible

**Comment by MikeSchulze** [comment]
Ok here my findings.

There are two problems in your project

1) You have configured a custom test folder *Tests* which is not taken into account when running the test, I will file an extra bug for that
2) Your test-suite has no namespace, which is the cause that the test-suite is not found.

Therefore currently valid until these bugs are fixed:

* Always span a namespace around the test-suite.
* Use the default settings for test folders.
