### ISSUE TITLE
GD-263: Changing the the `Test Root Folder` results in no test found anymore

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit3#263]
**The used Godot version:**
all

**OS including version:**
all

**Describe the bug**
After changing the `Test Root Folder` settings to `Tests` my tests are not executed anymore.
![image](https://user-images.githubusercontent.com/347037/170860984-861cc8d5-b6a9-48d1-9778-c137d9f1040a.png)

**Steps to Reproduce**
* create a folder `Tests` in your root
* place a test-suite in
* change the settings `Test Root Folder` settings to `Tests` 
* run tests for this folder

The inspector is empty

**Minimal reproduction project:**

**Comment by musicm122** [comment]
This might be related but, if I use the default folder and generate a test It uses the absolute root directory instead of the test directory relative to my test.
Expected folder:
![image](https://user-images.githubusercontent.com/725185/170877287-e4c73d6e-e4c4-4666-a570-550724e5ef4c.png)

Actual folder:
![image](https://user-images.githubusercontent.com/725185/170877259-093d487b-41d3-4a28-8eb4-cf763703e6d7.png)

**Comment by MikeSchulze** [comment]
Thanks for the additional information, I will take it into account.

**Comment by MikeSchulze** [comment]
@musicm122 the property defines the folder where tests should be created.
Test-suites will be generated relative to the source file.

func test_resolve_test_suite_path_project() -> void:
	# if no `src` folder found use test folder as root
	assert_str(resolve_path("res://foo.gd")).is_equal("res://_test_/foo_test.gd")
	assert_str(resolve_path("res://project_name/module/foo.gd")).is_equal("res://_test_/project_name/module/foo_test.gd")
	# otherwise build relative to 'src'
	assert_str(resolve_path("res://src/foo.gd")).is_equal("res://_test_/foo_test.gd")
	assert_str(resolve_path("res://project_name/src/foo.gd")).is_equal("res://project_name/_test_/foo_test.gd")
	assert_str(resolve_path("res://project_name/src/module/foo.gd")).is_equal("res://project_name/_test_/module/foo_test.gd")
	
func test_resolve_test_suite_path_plugins() -> void:
	assert_str(resolve_path("res://addons/plugin_a/foo.gd")).is_equal("res://addons/plugin_a/_test_/foo_test.gd")
	assert_str(resolve_path("res://addons/plugin_a/src/foo.gd")).is_equal("res://addons/plugin_a/_test_/foo_test.gd")
