### ISSUE TITLE
Method to yield for a signal (up to a timeout) without asserts

### ISSUE THREAD

**Issue by nightblade9** [MikeSchulze/gdUnit3#279]
I'm planning to port over tests from GUT. One of the missing pieces of functionality in gdUnit3 is the ability to do something like this:

```gdscript
yield(yield_to(monster, "moved", 1.0), YIELD)
```

The above code snippet waits for `monster` to emit the `moved` signal, but doesn't assert anything (which is important, because if I add assertions, it looks like I care about the monster moving; I don't, it's just something I need to be able to test what I really want.)

It looks like there's a way to do this in gdUnit3, with assertions, but that ends up testing things I don't need (can lead to flakiness, makes the test look more complicated than it is, etc.)

**Comment by MikeSchulze** [comment]
Hi @nightblade9,

There is already a function available on the Scene Runner 

https://mikeschulze.github.io/gdUnit3/advanced_testing/sceneRunner/#await_signal_on

You have to use the scene runner to await for a specific signal for a specific object.

**Comment by nightblade9** [comment]
Perfect, thank you!

**Comment by MikeSchulze** [comment]
> Perfect, thank you!

just for completness without scene runner
```
class Monster extends Node:
	
	signal move(value)
	
	var _pos :float = 0.0
	
	func _process(_delta):
		_pos += 0.2
		emit_signal("move", _pos)
		prints("emit_signal","move", _pos)

func test_wait_signal() -> void:
	var monster = Monster.new()
	add_child(monster)
	prints("signal wait start")
	yield(await_signal_on(monster, "move", [1.0]), "completed")
	prints("signal wait end")
       

```
