### ISSUE TITLE
Run Tests on Device

### ISSUE THREAD

**Issue by FeralBytes** [MikeSchulze/gdUnit3#283]
**Is your feature request related to a problem? Please describe.**
I think the only feature that I see GDUnit3 missing compared to GUT is the ability to run the tests in game. For instance sometimes weed bugs out on other peoples devices by creating tests around my assumptions on their device then I can give them the game and have them run the tests to see if I am correct. This very handy for mobile devices.

**Describe the solution you'd like**
I would like to be able to call some code from a scene and have it execute the tests and display the results. I also need a signal or variable that I can check to know when the tests are finished running and I would like to be able to retrieve results.

**Describe alternatives you've considered**
I am still very new to GDUnit3 and perhaps this is already doable. But with few examples I do not see how I could achieve the same thing and call all of my tests.

**Additional context**
N/A.

**Comment by MikeSchulze** [comment]
hi @FeralBytes,

to test Godot scenes you have to use the [scene_runner](https://mikeschulze.github.io/gdUnit3/advanced_testing/sceneRunner/) where is well documented.
The Tutorials section is work in progress and needs to be updated.

If you wan't you can also download the advanced examples direct over the GdUnit3 tool.
![image](https://user-images.githubusercontent.com/347037/174728675-1bad2d33-5a34-4f3f-9538-b9b517b8d930.png)
<img width="293" alt="image" src="https://user-images.githubusercontent.com/347037/174728811-20e2403f-9620-4ac3-a19e-693889a5eeb3.png">

If you have future question feel free to join the discord server linked on the main page.

**Comment by MikeSchulze** [comment]
@FeralBytes is this feature request still valid?

**Comment by MikeSchulze** [comment]
closed for now, will be reopen if it need
