### ISSUE TITLE
assert_null()

### ISSUE THREAD

**Issue by FeralBytes** [MikeSchulze/gdUnit3#284]
**Is your feature request related to a problem? Please describe.**
I would like to have an assert for null. I am currently working around with assert_bool(_spy_scene.TheContainer == null).is_true(), but assert_null() would be more concise.

**Describe the solution you'd like**
To have an assert function that checks if the value is equal to null.

**Describe alternatives you've considered**
assert_that(null_value).is_equal(null)  Failed stating expecting 'Null' but was Null.
assert_bool(_spy_scene.TheContainer == null).is_true()  This works.
**Additional context**
N/A.

**Comment by MikeSchulze** [comment]
hi @FeralBytes,

please read first the documentation of [GdUnit3 Asserts](https://mikeschulze.github.io/gdUnit3/asserts/index/) asserts
GdUnit Asserts are different technics as other test frameworks and uses typed asserts.

Do not write boolean asserts!
`assert_bool ( a == 10).is_true()` 

You have to use the assert api to verify what you want.
The correct syntax is:
`assert_int(a).is_equal(10)`

The GdUnit3 asserts provides already verification for null values
For your example you have to write
`assert_obj(_spy_scene.TheContainer).is_null()`
or
`assert_that(_spy_scene.TheContainer).is_null()`

**Comment by FeralBytes** [comment]
OK, thanks for the examples!
