### ISSUE TITLE
GD-289: Spy do not copies initalizied variables

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit3#289]
**The used Godot version:**
all

**OS including version:**
all

**Describe the bug**
I am trying to spy on an instance, the spy object has invalid/unset variables.

**Steps to Reproduce**
* Create a simple class and initialize a variable in the constructor.
* create a spy on this instance
* check the variable on the spy object
The variable is not set.

**Minimal reproduction project:**

res://addons/gdUnit3/test/mocker/resources/TestPersion.gd
```
extends Object


var _name

func _init(name :String):
	_name = name

func name() -> String:
	return _name
```

```

func test_spy_copied_class_members():
	var instance = auto_free(load("res://addons/gdUnit3/test/mocker/resources/TestPersion.gd").new("user-x"))
	assert_str(instance.name()).is_equal("user-x")
	
	# spy it
	var spy_instance = spy(instance)
	
	# verify members are inital copied 
	assert_str(spy_instance.name()).is_equal("user-x") <--- Fails
````

**Comment by FeralBytes** [comment]
Additionally the spy is not tracking interactions correctly. For instance this code snippet passes even though I clearly called set_().
```
func test_set_matches_get():
    _spy = spy(instance.Data.new())
    verify_no_interactions(_spy)
    _spy.set_("Test", 1)
    verify(_spy, 0).set_("Test", 1)
    #verify(_spy, 1).register_(any_string(), any_int())
    assert_int(_spy.get_("Test")).is_equal(1)
 ```
This test passes any ways, even though I set verify to 0.

**Comment by FeralBytes** [comment]
But of note the default methods of the class such as emit_signal are correctly tracked by verify and you can check is a signal was emitted or not.

**Comment by MikeSchulze** [comment]
Thanks for the additional infos, i will take in account.

**Comment by MikeSchulze** [comment]
> Additionally the spy is not tracking interactions correctly. For instance this code snippet passes even though I clearly called set_().
> 
> ```
> func test_set_matches_get():
>     _spy = spy(instance.Data.new())
>     verify_no_interactions(_spy)
>     _spy.set_("Test", 1)
>     verify(_spy, 0).set_("Test", 1)
>     #verify(_spy, 1).register_(any_string(), any_int())
>     assert_int(_spy.get_("Test")).is_equal(1)
> ```
> 
> This test passes any ways, even though I set verify to 0. You can also test it with verify_no_more_interactions(_spy) and it would still pass.

this is correct you have forget to create the property first.
You have to read the documentation ;)
```
void set(property: String, value: Variant)

Assigns a new value to the given property. If the property does not exist, nothing will happen.

Note: In C#, the property name must be specified as snake_case if it is defined by a built-in Godot node. This doesn't apply to user-defined properties where you should use the same convention as in the C# source (typically PascalCase).
```

Try without a spy it will fails with the same error, a resource has no properties by default
```
func test_set_matches_get():
	var data = BackGroundLoading.Data.new("")
	
	data.set("Test", 1)
	
	#verify(_spy, 1).register_(any_string(), any_int())
	assert_int(data.get("Test")).is_equal(1)
```

Try on a node instance you see it works as expected
```
func test_node_set_matches_get():
	var data :BackGroundLoading = auto_free(BackGroundLoading.new())
	
	data.set("name", "abc")
	
	assert_str(data.get("name")).is_equal("abc")

func test_node_set_matches_get_with_spy():
	var spy :BackGroundLoading = spy(auto_free(BackGroundLoading.new()))
	
	spy.set("name", "abc")
	verify(spy, 1).set("name", "abc")
	
	assert_str(spy.get("name")).is_equal("abc")
```

**Comment by FeralBytes** [comment]
To clarify there is a misunderstanding here. I am calling .set_(), notice the trailing underscore. This is my own method on the class that I am testing, not a method on GDUnit3 or the spy() class.
Thank you for your help.

**Comment by MikeSchulze** [comment]
Ok, my fould ;)
Can you provide a small example to reproduce please
