### ISSUE TITLE
GD-293: EditorPlugin object leak

### ISSUE THREAD

**Issue by Rubonnek** [MikeSchulze/gdUnit3#293]
**The used Godot version:** 3.x branch at commit 875a0dba5a096fd91dae3ebe258217ea6359c095

**OS including version:** Arch Linux

**Describe the bug** EditorPlugin object leak

**Steps to Reproduce**
1. Run on a terminal:
```
cd /path/to/gdUnit3
godot -e --verbose
```
2. Close the Editor and you'll see the following message on the terminal:
```
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2070)
Leaked instance: EditorPlugin:20272 - Node name: 
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
Orphan StringName: EditorPlugin
StringName: 1 unclaimed string names at exit.
```
**Minimal reproduction project:**

N/A -- this is an issue with gdUnit3

**Comment by MikeSchulze** [comment]
thanks for reporting

I have to investigate, i'm able to reproduce
