### ISSUE TITLE
GD-30: Add check to verify if a signal was emitted

### ISSUE THREAD

**Issue by afonsolage** [MikeSchulze/gdUnit3#30]
Checked the whole documentation and didn't saw any mentions about signals. At moment, is it possible to check if a signal was emitted or even if some object connected to anothers signals?

Anyway, loving the lib :heart:

**Comment by MikeSchulze** [comment]
This is the missing part, sorry.

I will add this soon.

**Comment by MikeSchulze** [comment]
you can use mock or spy to verify if a signal is emited.
```
class ClassWithSignal:
	signal test_signal_a
	signal test_signal_b
	
	func foo(arg :int) -> void:
		if arg == 0:
			emit_signal("test_signal_a", "aa")
		else:
			emit_signal("test_signal_b", "bb", true)


func test_mock_verify_emit_signal():
	var mocked_node :ClassWithSignal = mock(ClassWithSignal, CALL_REAL_FUNC)
	assert_that(mocked_node).is_not_null()
	
	mocked_node.foo(0)
	verify(mocked_node, 1).emit_signal("test_signal_a", "aa")
	verify(mocked_node, 0).emit_signal("test_signal_b", "bb", true)
	reset(mocked_node)

	mocked_node.foo(1)
	verify(mocked_node, 0).emit_signal("test_signal_a", "aa")
	verify(mocked_node, 1).emit_signal("test_signal_b", "bb", true)

```
But needs first to finisch https://github.com/MikeSchulze/gdUnit3/issues/38

**Comment by MikeSchulze** [comment]
@afonsolage you are ok to close this issue when #38 i merged?

If this cover all your needs as i described in the example below?

**Comment by MikeSchulze** [comment]
hi @afonsolage i will close this issue because you can verify it by using a spy and verify if the signal was emited
`verify(spy, 0).emit_signal([signal_name], <args>)`
