### ISSUE TITLE
GD-303: Improve reporting for array_asserts

### ISSUE THREAD

**Issue by FeralBytes** [MikeSchulze/gdUnit3#303]
The current array div report is not helpful and rather confusing
![image](https://user-images.githubusercontent.com/347037/181924893-9c6fa157-1f69-4fcb-87e9-4b09fdb7f21a.png)

**Describe What**
Improve the GD Unit Plugin- GdUnitInspector->MainPanel/report/ScrollContainer/list to have three lines of output per test result as compared to the current two.. 
1: Expecting (No Color Diff)
2: But Was (No Color Diff)
3: Diff (Full Color Diff)

**Describe Why**
Quickly reading the current output is not easy. It can be very confusing on larger outputs, such as Arrays or Dictionaries, to compose what specifically the output was versus what was expected as the text is all output as a diff each time which is a mixture of both and it is often split up through out the line as a mixture of expected and received values. So I purpose making this output more clear by keeping the first line as only what the expected value was, the second line as only what the received value was, and a third line that will perform the color diff.

**Dev hints**
res://addons/gdUnit3/src/ui/parts/InspectorTreePanel.tscn

**Comment by MikeSchulze** [comment]
Thank you very much for the feedback.

Yes they are right that the report can be improved by better visualization of the differences.
I think that visualizing large arrary differences is also a problem.
It would be good to provide a more detailed report view that can be displayed by double clicking on the report.

**Comment by MikeSchulze** [comment]
@FeralBytes what do you think?
![image](https://user-images.githubusercontent.com/347037/181924766-ffe65eb2-c4ec-43bb-aff6-06fda63d6bf4.png)

**Comment by FeralBytes** [comment]
If you wanted to keep it to only be 2 lines, then the above image is much easier to read and much easier to tell what is different.

**Comment by MikeSchulze** [comment]
Yes, that should be enough, I will now add an index value inspector to show the wrong values in a compact view

**Comment by MikeSchulze** [comment]
so finally it will now look like

`assert_array([1, 2222, 3, 4, 5, 6]).is_equal([1, 2, "this is a message", 4])`
![image](https://user-images.githubusercontent.com/347037/182020852-f92df9e2-3d84-432e-9448-8d05c4139c6b.png)

**Comment by FeralBytes** [comment]
Thank you! This is much better.
