### ISSUE TITLE
GD-31: Add support to mock and spy on Scenes

### ISSUE THREAD

**Issue by afonsolage** [MikeSchulze/gdUnit3#31]
**Is your feature request related to a problem? Please describe.**
`gdUnit3` supports only mocking objects, but not the scene itself, so if I need to mock a object from a saved scene (`PackedScene`) I can't (or at least I don't know how).

**Describe the solution you'd like**
It should be nice if we can mock the object or the scene, depending on the extension of what is beign called on the mock function:
```gdscript
var mocked_scene = mock("res://scenes/player.tscn", CALL_REAL_FUNC)
self.add_child(mocked_scene)

mocked_scene.do_some_mocked_function()
```

**Describe alternatives you've considered**
I've tried to mock the object script and change the scene object instance at runtime, but I think that isn't possible.

**Additional context**
I have a lot of scenes, like `Player.tscn` or `Mob.tscn` which has functions that depends on the scene tree it self, like check collisions using a `RayCast` or even check if a child node exists.

**Comment by MikeSchulze** [comment]
Yes it is currently not possible to mock or spy on a scene. :(

- marked as feature request

**Comment by afonsolage** [comment]
I made some research and got something, but still not working as expected. The main problem with current implementation on mock in order to mock scripts, is because it returns the instance itself, not the gdscript. I made a copy of the mock function named `mock_scene` and `build_scene` just to test and made it return the `mock` before calling `instance`:

```gdscript
static func build_scene(clazz, mock_mode :String, memory_pool :int, debug_write = false):
	var push_errors := is_push_error_enabled()
	if not is_mockable(clazz, push_errors):
		return null
	
	var clazz_name :String
	var clazz_path := GdObjects.extract_class_path(clazz)
	if clazz_path.empty():
		clazz_name = GdObjects.extract_class_name(clazz).value()
	else:
		clazz_name = GdObjects.extract_class_name_from_class_path(clazz_path)
	
	var function_doubler := MockFunctionDoubler.new(push_errors)
	var lines := load_template(GdUnitMockImpl, clazz_name)
	lines += double_functions(clazz_name, clazz_path, function_doubler)
	
	var mock := GDScript.new()
	mock.source_code = lines.join("\n")
	
	if debug_write:
		mock.resource_path = GdUnitTools.create_temp_dir("mock") + "/Mock%s.gd" % clazz_name
		Directory.new().remove(mock.resource_path)
		ResourceSaver.save(mock.resource_path, mock)
	var error = mock.reload(true)
	if error != OK:
		push_error("Critical!!!, MockBuilder error, please contact the developer.")
		return null
		
	return mock
```

and then:

```gdscript
	var mock = mock_scene(__source, CALL_REAL_FUNC)
	var scene_res := load("res://scenes/mobs/mob.tscn")
	mob_scene = scene_res.instance()
	mob_scene.set_script(mock)
	add_child(mob_scene)
```

with this I was able to get a mocked scene working, but for some reason that I don't know, the `onready` variables on original script won't run. So when I try to run the following test:

```gdscript
func test_set_state() -> void:
	mob_scene.translation = Vector3(1, 2, 3)
	mob_scene.rotation_degrees = Vector3(4, 5, 6)
	mob_scene._animation_tree.set("parameters/speed/blend_amount", 7)

	mob_scene.set_state({
		"P": Vector3(3, 2, 1),
		"R": Vector3(6, 1, 3),
		"A": 3,
	})

	assert_that(mob_scene.translation == Vector3(3, 2, 1)).is_true()
	assert_that(mob_scene.rotation_degrees == Vector3(6, 1, 3)).is_true()
	assert_that(mob_scene._animation_tree.get("parameters/speed/blend_amount")).is_equal(3)
```

it fails because `mob_scene._animation_tree` is null since it's a `onready var` inside the original class:

```gdscript
onready var _animation_tree := $AnimationTree
```

If I was able to figure it out, maybe I can use mock classes, until you officially add it :crossed_fingers: .

Also, noticed a "bug", that I'll open another issue soon. I use `snake_case.gd` on my class files, so when I first used `mock` it was trying to get a `clazz_name` based on the name of my file, which in that case was `mob.gd` but the class itself was `Mob`. I had to change to `Mob.gd` using `PascalCase` ir order to `mock` work.

**Comment by afonsolage** [comment]
Gotcha! I noticed the `mock_mode` was not set. So I set it and it worked fine!

```gdscript
func before_test() -> void:
	var mock = mock_scene(__source, CALL_REAL_FUNC)
	var scene_res := load("res://scenes/mobs/mob.tscn")
	mob_scene = scene_res.instance()
	mob_scene.set_script(mock)
	mob_scene.__set_singleton()
	mob_scene.__set_mode(CALL_REAL_FUNC)
	add_child(mob_scene)
```

I'll try to wrap up it and make a clean `mock` function, to mock both scripts and scenes. And I'll keep doing my tests, to see if it working fine

**Comment by afonsolage** [comment]
So, in the end, here what I did, now more organized:

1. Add a new parameter on `GdUnitMockBuilder.build` in order to know if the build should instanciate the mock, which default value of `true`
```gdscript
static func build(clazz, mock_mode :String, memory_pool :int, instanciate = true, debug_write = false):
```

2. Add a check on this new added parameter. If it should instanciate, do it, else, return just the mock (`GDScript`): 
```gdscript
	if instanciate:
		var mock_instance = mock.new()
		mock_instance.__set_singleton()
		mock_instance.__set_mode(mock_mode)
		return GdUnitTools.register_auto_free(mock_instance, memory_pool)
	else:
		return mock
```

3. Finally, if the build parameter is a `PackedScene` or ends with ".tscn", this is a scene mock, so instanciate the scene and change the script, else do as usual:
```gdscript
	if clazz is PackedScene or clazz.ends_with(".tscn"):
		var packed_scene = clazz if clazz is PackedScene else load(clazz)
		var scene_instance = packed_scene.instance()
		var script_path = scene_instance.get_script().get_path()
		var mock = build(script_path, mock_mode, memory_pool, false)
		scene_instance.set_script(mock)
		scene_instance.__set_singleton()
		scene_instance.__set_mode(mock_mode)
		return scene_instance
	elif not is_mockable(clazz, push_errors):
		return null
```

4. But this let us with a problem when adding to scene tree, because some `Node` methods was mocked and this broke something, so let's add scene methods to "blocklist" on `GdUnitClassDoubler.gd`:
```gdscript
const EXCLUDE_VIRTUAL_FUNCTIONS = [
	# Object
	"_get", 
	"_get_property_list", 
	#"_init", 
	"_notification", 
	"_set", 
	"_to_string",
	# Resource
	"_setup_local_to_scene",
	# Node
	'_enter_tree',
	'_exit_tree',
	'_process',
	'_draw',
	'_physics_process',
	'_input',
	'_unhandled_input',
	'_unhandled_key_input',
	]
```

That's it. Now to actually mock the scene:
```gdscript
func before_test() -> void:
	mob_scene = mock("res://scenes/mobs/mob.tscn", CALL_REAL_FUNC)
	add_child(mob_scene)
```

or even:
```gdscript
func before_test() -> void:
	var packed_scene = load("res://scenes/mobs/mob.tscn")
	mob_scene = mock(packed_scene, CALL_REAL_FUNC)
	add_child(mob_scene)
```

That's it. Now I'll keep testing!

**Comment by MikeSchulze** [comment]
Thanks for investigate to mock a scene, your help is very welcome ;)


I am currently working on a command line tool. That still needs some fine-tuning but is mostly already done. After that I will take care of the support for PackedScenes

**Comment by afonsolage** [comment]
Np, I'm fine with my custom, it is working (at least for now), but noticed that we can't mock `emit_signal` when using parameters, or at least, need to address it, since original `emit_signal` is a `varargs`, which isn't available on GDScript.

Keep that good work man!

**Comment by clemens-tolboom** [comment]
@afonsolage can you make this in a PR (as a WIP)? Or is that not efficient?
