### ISSUE TITLE
Unable to mock script which uses snake_case naming convention

### ISSUE THREAD

**Issue by afonsolage** [MikeSchulze/gdUnit3#32]
**The used Godot version:**
3.3-rc6

**OS including version:**
Ubuntu 20.04 x64 x11 GTX 1650M (proprietary drives)

**Describe the bug**
When trying to mock a script which has a `snake_case.gd` naming convention, `gdUnit3` tries to use the file name to find the class, so if I'm trying to mock a class, named `main_player.gd` or `mob.gd`, `gdUnit3` will extends `main_player` and `mob` classes, which doesn't exists.

Since `snake_case` is the convention recomended by [godot style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#file-names), many users will have the same problem.

**Steps to Reproduce**
1. Create a new script using `snake_case.gd`
2. Try to create a mock of this script
3. Run any tests and the error will appear

**Minimal reproduction project:**
N/A

**Comment by afonsolage** [comment]
I made a small and quick fix, but I don't know if it's the best way. Right after the `clazz_name` definition, on `GdUnitMockBuilder.build` I've added the following:

```gdscript
	if "_" in clazz_name or clazz_name == clazz_name.to_lower():
		var result = PoolStringArray()
		var prev_is_underscore = false
		for ch in clazz_name:
			if ch=='_':
				prev_is_underscore = true
			else:
				if prev_is_underscore:
					result.append(ch.to_upper())
				else:
					result.append(ch)
				prev_is_underscore = false

		result[0] = result[0].to_upper()
		clazz_name = result.join('')
```

The logic I got from [here](https://gist.github.com/me2beats/443b40ba79d5b589a96a16c565952419). It is working fine for my tests cases.

**Comment by MikeSchulze** [comment]
Thanks for submiting this issue, i will have a deeper look to understand the problem.

**Comment by MikeSchulze** [comment]
@afonsolage you can alternative use the class name to mock the class instead by path.

```
mock(main_player)
```
It needs onyl to add the class name definition in your class
```
class_name main_player
```

The fix is now in master and you can mock by class path or name as you want.

**Comment by afonsolage** [comment]
I'll try it, before even using the `class_name` (which was in PascalCase - MainPlayer) didn't worked, but I'll give a try and post here.

**Comment by afonsolage** [comment]
It worked for `main_class.gd`, but not for `mob.gd`, since mob.gd is `snake_case` but doesn't have underscore. Something like that would fix:

```gdscript
	# handle snake_case class names, only if clazz path available and is a GdScript
	if "_" in clazz_name and not clazz_path.empty() and (clazz_path[0].find(".gd") != -1):
		return "'%s'" % clazz_path[0]
	elif not ClassDB.class_exists(clazz_name):
		return "'%s'" % clazz_path[0]
	return clazz_name
```

Add a new test case using a `lowercaseonly.gd` test file and you should get the problem

**Comment by MikeSchulze** [comment]
After deeper investigation It seams to be it is not a snake case issue.
The doubler try to extend by class name but the class has no class_name defined.

So i need to deside to extend by existing class_name or class_path

**Comment by MikeSchulze** [comment]
pushed new fix to master

**Comment by afonsolage** [comment]
It's working fine now! Thanks!
