### ISSUE TITLE
GD-325: Common class names cause naming collisions

### ISSUE THREAD

**Issue by rgson** [MikeSchulze/gdUnit3#325]
**The used Godot version:**

3.5 stable.

**Describe the bug**

gdUnit3 classes with common `class_name`s cause naming collisions with users' code.

```
Loading GdUnit3 Plugin success
 res://src/Fonts.gd:1 - Parse Error: Unique global class "Fonts" already exists at path: res://addons/gdUnit3/src/ui/Fonts.gd
```

**Steps to Reproduce**

1. Create a script with `class_name Fonts`.
2. Install gdUnit3.

---

I suggest prepending `GdUnit` to all class names to avoid collisions. Many classes have this prefix already.

**Comment by MikeSchulze** [comment]
Thanks for reporting,

I have to change it to GdUnitFont.gd to prevent class name conflicts.
