### ISSUE TITLE
Ask for consent before downloading anything from the update server

### ISSUE THREAD

**Issue by Goutte** [MikeSchulze/gdUnit3#330]
It is terrifying, knowing afterwards that content from a server has been injected into the editor, even if it's only bbcode.

**Describe the solution you'd like**
Ask for consent before checking for updates.

**Describe alternatives you've considered**
A hot beverage and frenzied research into bbcode injection attacks.

**Additional context**
This plugin is amazing, thanks !

**Comment by MikeSchulze** [comment]
I have been waiting for this :)
There is no danger for crosscripts or code injection.
The source is markdown and is only rendered internally via bbcode. I have full control what is taken and what is not.
https://github.com/MikeSchulze/gdUnit3/blob/master/addons/gdUnit3/src/update/GdMarkDownReader.gd

**Comment by MikeSchulze** [comment]
close as clarified, there is no option to crosscripts or code injection.
