### ISSUE TITLE
GD-331: Timeout of test cases lead to crash of test execution

### ISSUE THREAD

**Issue by mashumafi** [MikeSchulze/gdUnit3#331]
**The used Godot version:**
3.5

**OS including version:**
Max OS, Windows

**Describe the bug**
https://github.com/MikeSchulze/gdUnit3/blob/master/addons/gdUnit3/src/core/GdUnitExecutor.gd#L375 `duplicate` fails sometimes. I bumped the timeout for tests and it looks like that resolved the issue. This leads me to believe this is related to timeout logic. Maybe it deletes the node which causes `duplicate` to fail. I have not had time to investigate further yet.

**Steps to Reproduce**
* Run this simple test that times out
```
extends GdUnitTestSuite

func test_timeout(timeout=1500):
	var node := Node.new()
	node.filename = "does_not_exist"
	add_child(node)
	yield(get_tree().create_timer(60), "timeout")
```

Errors:
![image](https://user-images.githubusercontent.com/347037/198867366-5901b36b-a40a-413d-99b5-622f5769a7ec.png)

# Reaults:
A node must have an valid filename. Means the file must exists or you have to set to an empty string.

**Minimal reproduction project:**

**Comment by MikeSchulze** [comment]
hi @mashumafi thanks for reporting it.

This sounds strange, because I have an internal test coverage for timeouts and all these tests run successfully.
The default timeout for a test case is 300s.

So how long is your test case running?
Can you please add more details, e.g. steps to reproduce.
Can you add the console/debug log error.
Without this information I can't reproduce the failure behavior.

**Comment by mashumafi** [comment]
I see theses errors:

E 0:00:12.516   _load: Resource file not found: res://levels/01_BASICS.maze::3.
  <C++ Error>   Condition "!file_check->file_exists(p_path)" is true. Returned: RES()
  <C++ Source>  core/io/resource_loader.cpp:275 @ _load()
  <Stack Trace> GdUnitExecutor.gd:375 @ clone_test_suite()
                GdUnitExecutor.gd:356 @ Execute()
                GdUnitExecutor.gd:0 @ execute_test_case_single()
                GdUnitExecutor.gd:0 @ test_after()

E 0:00:12.516   _duplicate: Condition "res.is_null()" is true. Returned: nullptr
  <C++ Source>  scene/main/node.cpp:2173 @ _duplicate()
  <Stack Trace> GdUnitExecutor.gd:375 @ clone_test_suite()
                GdUnitExecutor.gd:356 @ Execute()
                GdUnitExecutor.gd:0 @ execute_test_case_single()
                GdUnitExecutor.gd:0 @ test_after()

This occurs during `yield` in my test. They run for 5 minutes but I reduce timeout to 15s and this error occurs earlier.

**Comment by mashumafi** [comment]
I do have a line of code `stage.filename = uri()`, maybe setting the filename is messing with the duplicate function? I'm not sure why it needs to duplicate and why it fails with a low timeout value.

**Comment by MikeSchulze** [comment]
can you add your testsuite or an small example to reproduce please?

**Comment by mashumafi** [comment]
I'll try to create an map and upload it soon

**Comment by mashumafi** [comment]
hey this reproduces the issue:

```gdscript

	var node := Node.new()
	node.filename = "does_not_exist"
	add_child(node)
	yield(get_tree().create_timer(60), "timeout")
```

**Comment by MikeSchulze** [comment]
@mashumafi wow thats simple code will end up in this error?
Let me verify, thanks for the example
