### ISSUE TITLE
Godot 4 support?

### ISSUE THREAD

**Issue by nightblade9** [MikeSchulze/gdUnit3#332]
Hi, are there any plans to support Godot 4? (I see a red badge in the README.)

I plan to use Godot 4 with C#. I don't think NUnit would work out-of-the-box (it would need to spin up a Godot instance for integration tests, plus the complication of debugging.)

**Comment by MikeSchulze** [comment]
;)
Is already an alpha released
https://github.com/MikeSchulze/gdUnit4/releases/tag/v4.0.0-alpha

You are welcome to support me.
I want to make the gd api stable first, followed by the c# api
