### ISSUE TITLE
GD-333: The identifier "Time" isn't declared in the current scope

### ISSUE THREAD

**Issue by NickHatBoecker** [MikeSchulze/gdUnit3#333]
**The used Godot version:**
Godot Engine v3.5.1.stable.official [6fed1ffa3]

**OS including version:**
Macbook Pro M1; MacOS Monterey 12.5.1

**Describe the bug**
In my project I have the following line of code:

```
var saveDate = Time.get_datetime_dict_from_system()
```

I added Continuous Integration with help of [official docs](https://mikeschulze.github.io/gdUnit3/faq/ci/#howto-deploy-with-github-action). In the CI log I get the following error:

```
Debugger Break, Reason: 'Parser Error: The identifier "Time" isn't declared in the current scope.'
```

Is there any fix to this? Can I check in my code if `Time` is declared and if not set a default?
Or can I globally mock the `Time` object?

**Comment by MikeSchulze** [comment]
Hi, `Time` was first introduced with Godot 3.5
have you addapt your CI workflow to the right version?
`image: barichello/godot-ci:3.4.4` -> `image: barichello/godot-ci:3.5.1`

**Comment by MikeSchulze** [comment]
@NickHatBoecker can you verify it please?

**Comment by NickHatBoecker** [comment]
@MikeSchulze Thank you so much, that was the case! I thought `Time` was a super old feature, so I didn't consider updating the version 🙈

**Comment by MikeSchulze** [comment]
nice, so i close as clarified
