### ISSUE TITLE
GD-337: Start an individual parameterised test from the GdUnit3 tab context menu

### ISSUE THREAD

**Issue by ZodmanPerth** [MikeSchulze/gdUnit3#337]
**Is your feature request related to a problem? Please describe.**
May be related to #336

**Describe the solution you'd like**
In a GdUnit3 inspector tab that is displaying the results of individual parameterised unit tests, I would like to be able to right-click an individual test result and select "Run Test" or "Debug Test" to execute a test run containing only the test with those parameters.

**Describe alternatives you've considered**
Being able to right-click the test parameter array in the code editor to run/debug individual tests would be an edge case.

**Additional context**
i.e. add to this context menu
![image](https://user-images.githubusercontent.com/546368/208322471-0af97276-f288-478e-9336-b433648e248c.png)

**Comment by MikeSchulze** [comment]
running a single parameterized test by select
![image](https://user-images.githubusercontent.com/347037/208470314-438b84cc-d5f8-4cc1-95f3-7ef8a8623b5b.png)

**Comment by ZodmanPerth** [comment]
🙌
