### ISSUE TITLE
GD-347: Allow to compare real vs int typed dictionary

### ISSUE THREAD

**Issue by ZodmanPerth** [MikeSchulze/gdUnit3#347]
**The used Godot version:**
v3.5.1.stable.official [6fed1ffa3]

**OS including version:**
Windows 11

**Describe the bug**
I'm using a dictionary in a parameterised test in GdUnit3 2.3.1.  The dictionary contains key/value pairs of type string/double.
When I define my expected value dictionary, I define the values using whole numbers (i.e. without the decimal point).
The difference report shows the actual values are identical to the expected values (see image).
![image](https://user-images.githubusercontent.com/546368/209413304-2a868fd8-6278-47c7-91a0-2ffb01a6a387.png)
The expected values in the above test run were defined as `{ left = 50, top = 50, right = 50, bottom = 50 }`.
As a workaround, if I define my expected values as `{ left = 50.0, top = 50.0, right = 50.0, bottom = 50.0 }` then the test passes.

**Steps to Reproduce**
1. Create a parameterised test containing a Dictionary expected value containing key/value pairs of type string/double.
2. Create a test parameter containing valid integer values
3. Run the test
4. Observe the assert fails but the "expecting" is the same as the "actual" in the report.

**Comment by MikeSchulze** [comment]
Hello, if you compare two dictionaries with different types, the result is always false.

Just try this
```gdscript
	var x := { "left" : 50, "top" : 50, "right" : 50, "bottom" : 50 }
	var y := { "left" : 50.0, "top" : 50.0, "right" : 50.0, "bottom" : 50.0  }
	prints(x == y)
```
is same result as use:
`assert_dict({ "left" : 50, "top" : 50, "right" : 50, "bottom" : 50 }).is_equal({ "left" : 50.0, "top" : 50.0, "right" : 50.0, "bottom" : 50.0 })`

Can you please add an example of your test for better understanding.

**Comment by ZodmanPerth** [comment]
Oh you're right.  My apologies.  I expected `x == y` to be true and that Godot would typecase the values to be the same at runtime.
This is not a bug then.  Please close.

**Comment by MikeSchulze** [comment]
hi @ZodmanPerth can you please add your testcase to fully understand your issue.

**Comment by ZodmanPerth** [comment]
This test passes:
```
func test_riffing() -> void:
	assert_that(50.0).is_equal(50)
```

Only the last test here passes.  I expected them all to.
I expect that implicit casing would occur between `50` and `50.0` as it does in the simple case.
```
# NOTE: This is the same test, formatted with different tabs for lining up vertically in GitHub and in Godot.
# Copy the Godot test for pasting in Godot.

# GitHub tab formatting
func test_dictionary_types(
	value : Dictionary,
	expected : Dictionary,
	test_parameters : Array = [
		[{ top = 50.0	, bottom = 50.0	, left = 50.0	, right = 50.0	},	{ top = 50	, bottom = 50	, left = 50	, right = 50	}],
		[{ top = 50.0	, bottom = 50.0	, left = 50.0	, right = 50.0	}, 	{ top = 50.0	, bottom = 50.0	, left = 50.0	, right = 50.0	}],
		[{ top = 50	, bottom = 50	, left = 50	, right = 50	}, 	{ top = 50.0	, bottom = 50.0	, left = 50.0	, right = 50.0	}],
		[{ top = 50	, bottom = 50	, left = 50	, right = 50	}, 	{ top = 50	, bottom = 50	, left = 50	, right = 50	}],
	]
) -> void:
	assert_that(value).is_equal(expected)

# Godot tab formatting
func test_dictionary_types(
	value : Dictionary,
	expected : Dictionary,
	test_parameters : Array = [
		[{ top = 50.0	, bottom = 50.0	, left = 50.0	, right = 50.0	},	{ top = 50		, bottom = 50	, left = 50		, right = 50	}],
		[{ top = 50.0	, bottom = 50.0	, left = 50.0	, right = 50.0	}, 	{ top = 50.0	, bottom = 50.0	, left = 50.0	, right = 50.0	}],
		[{ top = 50		, bottom = 50	, left = 50		, right = 50	}, 	{ top = 50.0	, bottom = 50.0	, left = 50.0	, right = 50.0	}],
		[{ top = 50		, bottom = 50	, left = 50		, right = 50	}, 	{ top = 50		, bottom = 50	, left = 50		, right = 50	}],
	]
) -> void:
	assert_that(value).is_equal(expected)
```

They also don't produce any failure report:

![image](https://user-images.githubusercontent.com/546368/209588857-c78385d1-19f1-49b7-bf54-33dec844bf5d.png)

**Comment by MikeSchulze** [comment]
The lack of bug reports is definitely a bug.
But the comparison of dictionarys with different types is Godot conform.

**Comment by MikeSchulze** [comment]
Update.
I found a bug on the UI side, the tree items were not unique and therefore updated incorrectly.
For the comparison problem I added a new property that allows to compare values in a type safe way.

```gdscript
func test_dictionary_div_number_types(
	value : Dictionary,
	expected : Dictionary,
	test_parameters : Array = [
		[{ top = 50.0,	bottom = 50.0,	left = 50.0,	right = 50.0},	{ top = 50, 	bottom = 50,	left = 50,  	right = 50}],
		[{ top = 50.0,	bottom = 50.0,	left = 50.0,	right = 50.0},	{ top = 50.0,	bottom = 50.0,	left = 50.0,	right = 50.0}],
		[{ top = 50,	bottom = 50,	left = 50,  	right = 50},	{ top = 50.0,	bottom = 50.0,	left = 50.0,	right = 50.0}],
		[{ top = 50,	bottom = 50,	left = 50,  	right = 50},	{ top = 50, 	bottom = 50,	left = 50,  	right = 50}],
	]
) -> void:
	# allow to compare type unsave
	ProjectSettings.set_setting(GdUnitSettings.REPORT_ASSERT_STRICT_TYPE_COMPARE, false)
	assert_that(value).is_equal(expected)
```
You can set this property explecit on a test or global at the settings
![image](https://user-images.githubusercontent.com/347037/209689339-536af25a-c279-4ab1-a659-4bae571513e2.png)

**Comment by ZodmanPerth** [comment]
Oooh nice.  Thank you.
