### ISSUE TITLE
GD-348: Add a scrollbar to the tree section of the report tab

### ISSUE THREAD

**Issue by ZodmanPerth** [MikeSchulze/gdUnit3#348]
**Is your feature request related to a problem? Please describe.**
No
  
  
**Describe the solution you'd like**

On the report tab the bottom half (differences section) has a scrollbar allowing me to see long lines, however the test name tree (top half) does not have a scrollbar.  In order to see test names with long descriptions I have to expand the tab column in the Godot Editor which reduces the screen real-estate for other things (such as the code editor)

A horizontal scrollbar needs to be added to the tree section in order to read lengthy test names (such as parameterised tests).
  
  
**Additional context**

A horizontal scrollbar serving the top section of the report should be visible in the circled area of this snapshot:

![image](https://user-images.githubusercontent.com/546368/209452146-17ffa02e-063f-49f1-ac22-54fe446759e2.png)

**Comment by MikeSchulze** [comment]
Yes thats a good point, i will add it.

**Comment by MikeSchulze** [comment]
Update!
This is an Godot bug and only fixed in Godot4
[Bug: HScrollBar in Tree](https://github.com/godotengine/godot-proposals/issues/2357)
[fix ](https://github.com/godotengine/godot/pull/49917)
