### ISSUE TITLE
GD-349: Line number in report is `-1` when running without debugger

### ISSUE THREAD

**Issue by ZodmanPerth** [MikeSchulze/gdUnit3#349]
**The used Godot version:**
v3.5.1.stable.official [6fed1ffa3]

**OS including version:**
Windows 11

**Describe the bug**
The line number on the report shows the correct line when debugging tests, but when running tests without the debugger the line number is reported as `-1`

Debug Time:
![image](https://user-images.githubusercontent.com/546368/209452332-1ba60876-7cee-4abe-a74d-d6777d4b0b9a.png)

Run Time:
![image](https://user-images.githubusercontent.com/546368/209452322-f0442fb2-66e2-4862-8867-ece61859199a.png)

**Steps to Reproduce**
1. Create a test with the reproduction method provided below
2. Run the test with debug
3. Observe the correct line number is reported
4. Run the test without debug
5. Observe the line number is reported as `-1`

**Minimal reproduction project:**
```
func test_lineNumber():
	assert_bool(false).is_true()
```

**Comment by MikeSchulze** [comment]
This is not a bug, Godot do not give a full stacktrace at runtime mode. 
This info is only available at debug mode.

I have to add this info to the documentation, to not confuse the user.

**Comment by ZodmanPerth** [comment]
In that case I suggest you remove the line number part of the report at runtime and only show it at debug time.
