### ISSUE TITLE
GD-375: Add code coverage metrixs

### ISSUE THREAD

**Issue by CameronJett** [MikeSchulze/gdUnit3#375]
Just started using the library and really appreciate it.  One thing I think would be great is a code coverage feature to just show which lines you haven't tested in each file and any if branches you haven't gone through.

**Comment by MikeSchulze** [comment]
Hi @CameronJett 
I have to agree with you absolutely, I would also like to have this feature. Unfortunately, there is no way to achieve this with the conventional engine means. If you know more or know a possibility I would be grateful for some hints.

**Comment by CameronJett** [comment]
I'm gonna try and look into how code coverage tools gather the information about what branches and lines are tested.  I think if there is a way to capture that data it can create an output folder with an html showing your files and lines.  It does sound like a ton of work so I just wanted to throw it out as a great feature.

**Comment by MikeSchulze** [comment]
there is current no easy way to du this, close and put into ice box
