### ISSUE TITLE
GD-376: Mocking of a class that uses a custom constructor fails if the argument contains `func` in its name

### ISSUE THREAD

**Issue by lars-hoeck** [MikeSchulze/gdUnit3#376]
**The used Godot version:**
Godot v3.1.5

**OS including version:**
ALL

**GdUnit3 Version**
GdUnit3 v2.4.1

**Describe the bug**
I just started to use gdUnit3 and read the Doc about mocking. I tried to mock a class and got errors. The problem was my class had an init(value), but i didnt know i had to put that in the mock.

**Steps to Reproduce**
Use the attached project and run the test.
[TestProject.zip](https://github.com/MikeSchulze/gdUnit3/files/10609845/Unit.Test.zip)

`Parser Error: Expected an identifier for an argument.`

**Findings**
The constructor uses `func` in the argument name where results in an parsing error.
`func _init(function_enum :int):`

## Workaround
Do not use `func` in argument names.

**Comment by MikeSchulze** [comment]
Hi @lars-hoeck 

You should not need to specify the constructor arguments when using a mock.
The mock will detect the constructor by default and use default arguments to construct it.

As Example
```gdscript
class MyClass:
	func _init(arg1 :String, arg2 :int):
		pass

func test_mock_with_constructor_args():
	var m = mock(MyClass)
	assert_that(m).is_not_null()
```
The mock was created successfully


Can you give me an example to reproduce your problem.

**Comment by lars-hoeck** [comment]
I was wrong, i have a different problem.
I get _Parse Error: Expcted an identifier for an argument_. in DEBUG
Here is a minimal project with the error.
[Unit Test.zip](https://github.com/MikeSchulze/gdUnit3/files/10609845/Unit.Test.zip)

**Comment by MikeSchulze** [comment]
Ok I can confirm that it is a bug.

The parser has a problem with arguments that have `func` in the argument name. 
`func _init(function_enum :int):`
After I changed the constructor to `func _init(fenum :int):` it works.

**Comment by lars-hoeck** [comment]
Lucky me :D 
When do u plan to release v2.4.2? Or should i rename my functions.

**Comment by MikeSchulze** [comment]
> Lucky me :D When do u plan to release v2.4.2? Or should i rename my functions.

For now please use the workaround, i currently working hard on GdUnit4 and needs all my time.
