### ISSUE TITLE
GD-378: Add a way to compare arrays of objects using is_same rather than is_equal

### ISSUE THREAD

**Issue by ACG8** [MikeSchulze/gdUnit3#378]
**The used Godot version:**

Godot version 3.5
GdUnit3 version 2.4.1

**OS including version:**

Microsoft Windows 10 Home 10.0.19045 Build 19045

**Describe the bug**

The contains_exactly_in_any_order method for GdUnitArrayAssert does not work correctly for arrays of Resources. If an array of Resources contains Resources that are not supposed to be contained, the assertion does not fail.

**Steps to Reproduce**

1. Create a new test script file extending GdUnitTestSuite
2. Add the following test function:

```
func test_example():
	var r1 = Resource.new()
	var r2 = Resource.new()
	var a1 = [r1, r2]
	var a2 = [r1]
	assert_array(a1).contains_exactly_in_any_order(a2)
```

The expected behavior is that this test fails since a1 contains r2 in addition to r1. However, it passes instead.

I tested the same behavior with integers instead of resources and it worked properly:

```
func test_example():
	var a1 = [1, 2]
	var a2 = [1]
	assert_array(a1).contains_exactly_in_any_order(a2)
```

```
line <n/a>: Expecting contains exactly elements:
 1, 2
 do contains exactly (in any order)
 1
but some elements where not expected:
 2
```

**Comment by ACG8** [comment]
Actually, it is even worse than I thought. It looks like different resources are not recognized as being different by GdUnit3:

```
func test_example():
	var r1 = Resource.new()
	var r2 = Resource.new()
	var a1 = [r1]
	var a2 = [r2]
	assert_array(a1).is_equal(a2)
	assert_object(r1).is_equal(r2)
	print(r1 == r2)
```
This passes, even though it shouldn't. (the print statement evaluates to false, confirming that Godot recognizes r1 and r2 as being different)

**Comment by ACG8** [comment]
Dug a little bit deeper. I have a custom class called Monster that extends from Resource:

```
class_name Monster
extends Resource


var alignment : int


func with_alignment(value: int) -> Monster:
	alignment = value
	return self
```

The following test behaves as expected (it fails):

```
func test_example():
	var r1 = Monster.new().with_alignment(Alignment.GOOD)
	var r2 = Monster.new().with_alignment(Alignment.EVIL)
	assert_object(r1).is_equal(r2)
```
```
line 20: Expecting:
 <Resource>
 but was
 <Resource>
```

But if I give them the same value for alignment, it passes:
```
func test_example():
	var r1 = Monster.new().with_alignment(Alignment.GOOD)
	var r2 = Monster.new().with_alignment(Alignment.GOOD)
	assert_object(r1).is_equal(r2)
```

So without looking at the implementation, it seems to me that Resource equality is looking at whether two resources contain the same data to determine whether they are the same. My assumption as a user would be that Resource equality would look at the object reference so that different objects containing the same data would not be considered equal.

Assuming I am correct, is it intentional that object equality treats different objects as equal if they contain the same values? If so, I would recommend making a note of that in the documentation.

**Comment by ACG8** [comment]
Sorry, just realized that the object assertions do in fact have [is_same](https://mikeschulze.github.io/gdUnit3/asserts/assert-object/#is_same), which does what I want.

So I suppose the only real issue is that the array assertions always use is_equal rather than is_same. So that is the only thing I would request - a way to compare objects in arrays using is_same rather than is_equal (assuming I understand how it works).

**Comment by MikeSchulze** [comment]
Hello @ACG8 this is not an error ;)

Yes, your analysis is correct, GdUnit compares objects on their parameter equality.
So two "empty" resources are the same in the end.
To compare on object reference level there is the `is_same` in `assert_object`.

```gdscript
func test_example():
	var r1 = Resource.new()
	var r2 = Resource.new()
	
	# will success
	assert_object(r1).is_equal(r2)
	# will fail, is not the same
	assert_object(r1).is_equal(r2).is_same(r2)
```

**Comment by ACG8** [comment]
Thanks! That is a very useful feature, now that I understand that it is not the only option. Is there a way to do the same thing for arrays of objects?

**Comment by MikeSchulze** [comment]
I understand your problem, this is not what a user expects at first ;)

It would probably be best to add a new option to disable the default depth comparison and then compare at object reference level. 

e.g. under 'Asserts'
`Strict object compare` - 'Enables/disables to comapare objects by reference only'
![image](https://user-images.githubusercontent.com/347037/219880581-6d969dd9-1bf2-4e70-a45c-3b90f22763d8.png)

**Comment by ACG8** [comment]
Yes, that sounds perfect. Thanks!

**Comment by MikeSchulze** [comment]
for now you can do it manually.
To disable the deep check open `res://addons/gdUnit3/src/core/GdObjects.gd` line 213
and change the default `deep_check :bool = true` to false

**Comment by ACG8** [comment]
Thanks! Super helpful. I really like GdUnit3, might make a tutorial video at some point.

**Comment by MikeSchulze** [comment]
> I really like GdUnit3, might make a tutorial video at some point.

Thank you very much.
I would be very grateful. unfortunately I currently have no time to make tutorials. Am with GdUnit4 under full load

**Comment by MikeSchulze** [comment]
I'm going to close this topic because the proposed solution is not practical.
By default, GdUnit performs a deep comparison because Godot Object does not provide an Equal method and testing only by reference would break a lot of existing tests.
It would be better to add a flag to the assert verification `is_equal` to explicitly decide whether to test for object reference or object content in the test.

Since GdUnit3 is only in maintenance and I don't want to implement any new features here I will move the topic to GdUnit4 and implement it there. 

Translated with www.DeepL.com/Translator (free version)
