### ISSUE TITLE
GD-38: Unable to mock functions that uses variadic arguments

### ISSUE THREAD

**Issue by afonsolage** [MikeSchulze/gdUnit3#38]
**The used Godot version:**
3.3-rc6

**OS including version:**
Ubuntu 20.04 x11 x64 Nvidia 1650M (proprietary drivers)

**Describe the bug**
When calling mocked function that uses variadic arguments using mocking mode `CALL_REAL_FUNC`, it fails, because the way mocked functions are current generated doesn't support variadic arguments.

1. Create a mocked node using `CALL_REAL_FUNC`
2. Attempt to call some function that uses variadic arguments, like `emit_signal` or `rpc_id`
3. Remember to use parameters, like `node.emit_signal("some_signal", var1, var2, var3)`
![image](https://user-images.githubusercontent.com/1176452/112763735-12727480-8fdc-11eb-941b-2ce150c6bc4c.png)

**Minimal reproduction project:**
[test_project_varargs.zip](https://github.com/MikeSchulze/gdUnit3/files/6217859/test_project_varargs.zip)

**Comment by afonsolage** [comment]
Dunno if this is a bug or can be seen as a feature request, because to fix the bug, one can just block the methods that uses variadic args, but supporting mock on variadic args is more complex than just blocking

**Comment by MikeSchulze** [comment]
I'm supriced ;) i was not aware that Godot supports variable arguments as an type.

I dit a short deeper investigation and found a way to detect if a function signature has an vararg argument.
So looks like is easy to fix

But is as so often undocumented internal Godot stuff ;(

**Comment by MikeSchulze** [comment]
https://github.com/godotengine/godot/issues/47449
