### ISSUE TITLE
GD-390: Tests hang when godot.log is not found

### ISSUE THREAD

**Issue by shadowbitdev** [MikeSchulze/gdUnit3#390]
**The used Godot version:** 3.5.2 (official)

**OS including version:** Windows 7 / Slackware 15 (current)

**Describe the bug**
Running tests hangs when the log file godot.log cannot be found

**Steps to Reproduce**
1. Open Project Settings
2. Go to General > Logging > File Logging
3. Change the Log Path, for example: user://logs/godot2.log
4. Run any test
5. The test show as running but never completes

Note:
An alternative to step 3 is to disable logging (even though this scenario is less likely)

**Minimal reproduction project:**
Any project: I have verified the bug with both my own game and one of the Pong demos installed through Steam

I think the issue is from GodotGdErrorMonitoring.gd
`func _init().("GodotGdErrorMonitor"):`
`	_godot_log_file = GdUnitSettings.get_log_path().get_base_dir() + "/godot.log"`
`	_report_enabled = is_reporting_enabled()`

Is there any reason to not get the path from the settings?
`_godot_log_file = ProjectSettings.get_setting("logging/file_logging/log_path")`

EDIT: code formatting

**Comment by MikeSchulze** [comment]
Thanks to report this bug.

I will take a look tomorrow on it.
And yes the hard coded logfile path looks wrong, i compared with the GdUnit4 version and it uses the configured Godot logpath.
