### ISSUE TITLE
all .cs files with namespace GdUnit3 are missing (were present in v2.2.6, gone since v2.3.0)

### ISSUE THREAD

**Issue by AD1337** [MikeSchulze/gdUnit3#393]
**The used Godot version:**
3.5.2

**Describe the bug**
I got a 'missing namespace GdUnit3' error. It's in Portuguese so I won't paste the exact error. The fact is that I downloaded the latest version of this addon and there are no .cs files that use the namespace GdUnit3.

The only mention of it is in the file `GdUnit3MonoAPI.cs`, which extends `GdUnit3.GdUnit3MonoAPI`. But that namespace is not mentioned anywhere else.

I looked at the older versions and it seems like files in that namespace existed from v2.2.6 back, but disappeared from v2.3.0 forwards.

**Steps to Reproduce**
Try running a mono project using the latest version of the plugin, I guess.

![missing namespace](https://github.com/MikeSchulze/gdUnit3/assets/2739479/1bc8a809-3921-48bf-90f6-7f07e829b93e)

**Comment by MikeSchulze** [comment]
It works as expected 
![image](https://github.com/MikeSchulze/gdUnit3/assets/347037/3bb3f4e6-95b1-4026-8eed-bd40b924888a)


Have you read the documentation to c#?
https://mikeschulze.github.io/gdUnit3/faq/C%23/

I just do:
using Godot `v3.5.3.stable.mono.official [6c814135b]` and install the gdUnit3 plugin from the AssetStore.
After activate I do the update it pops up and restart Godot.
Edit your csproj file and added the required parts.

Open it in VSCode and it builds without errors.

**Comment by AD1337** [comment]
It worked, thank you! :)
