### ISSUE TITLE
GD-44: Cannot save file "Saved 5 modified resource(s)"

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit3#44]
**The used Godot version:**
3.3.rc7

**OS including version:**

MacOS 11.2.3

**Describe the bug**

Running test works ... editing test subject or test file gives:

![image](https://user-images.githubusercontent.com/371014/113484324-02f59e80-94a8-11eb-92c8-565eca8685e6.png)

The file is not saved.

**Steps to Reproduce**

1. Add a GD file to test against
2. Create test
3. Test a function for that file
4. Run tests
5. Edit either file
6. Try to save
7. `Rerun unit tests`
8. File still not saved
9. `Rerun unit tests (debug)`
10. File gets saved! 

**Minimal reproduction project:**

File

```python
extends Reference

class_name StandaloneScript

func add(a:int, b:int) -> int:
	return a + b
```

Test file

```
# GdUnit generated TestSuite
class_name standalone_scriptTest
extends GdUnitTestSuite

# TestSuite generated from
const __source = 'res://standalone_script.gd'

func test_add() -> void:
	# remove this line and complete your test
	var t:StandaloneScript = StandaloneScript.new()
	var sum = t.add(2,2)
	assert_int(sum).is_equal(4)
```

**Comment by MikeSchulze** [comment]
@clemens-tolboom i can reproduce on v3.2.4.beta4 thanks for reporting
