### ISSUE TITLE
GD-61: Plugin errors out when enabled in Godot 3.3

### ISSUE THREAD

**Issue by nightblade9** [MikeSchulze/gdUnit3#61]
**The used Godot version:** 3.3

**OS including version:** Windows 10 Home

**Describe the bug**
When enabling the plugin, an error message appears: `Unable to load addon script from path: 'res://addons/gdUnit3/plugin.gd' There seems to be an error in the code, please check the syntax.`

**Steps to Reproduce**
- Create a new Godot project
- Go to AssetLib and search for GDUnit
- Download and install the plugin
- Go to Project > Project Settings > Plugins, and check the "Enable" checkbox for gdUnit3

The error message appears.

Strangely enough, enabling the plugin a second time, succeeds

**Comment by MikeSchulze** [comment]
thanks for reporting, i will investigate

**Comment by MikeSchulze** [comment]
merged in master 
v 0.9.3 - beta
