### ISSUE TITLE
GD-62: Add Option to Disable Orphan Checks

### ISSUE THREAD

**Issue by nightblade9** [MikeSchulze/gdUnit3#62]
Hi,

Is it possible to add a feature in GDUnit to ignore / not report orphan objects generated in tests?

I spent a fair bit of time investigating, adding `auto_free`, etc. and I think it's my test code that's faulty, not my production/game code. I would like to ignore this in the future (and just see passing tests instead of a lot of warning tests).

I just noticed that tests that show warnings when run, are failing when I debug; but when I run them, they show up as warnings, not as failures.

**Comment by MikeSchulze** [comment]
Hi,

yes i can add a option to enable/disable orphan detection ;)

`
I just noticed that tests that show warnings when run, are failing when I debug; but when I run them, they show up as warnings, not as failures.`

Can you please describe this issue in more detailed?
`show warnings when run` warnings yo mean orphans? 
` show up as warnings, not as failures.`  what kind of failure type?

**Comment by nightblade9** [comment]
I think this is actually two issues. For the first issue - can I enable/disable orphan detection - my only input is that, for my use-case, this should be something you can do globally (all tests), not on a test-by-test basis.

For the failures-as-warnings, I think these are the repro steps:

- Write a test that creates orphans
- Modify the test so that it fails, maybe something like `assert.that(true).is_equal(false)`
- Right-click the test-suite folder (I call mine `tests` usually) in the project tree and pick Run Tests

Expected: you should see one test failure
Actual: instead, you see one test with a warning (yellow colour) with no indication that it failed

If you debug the tests instead, Godot breaks at the failing points, so you can see the tests are actually failing.

**Comment by MikeSchulze** [comment]
Ok thanks for this additonal info, i will try to reproduce and open a new bug issue.

**Comment by nightblade9** [comment]
> You mean the icon state in the inspector like this?

Yes, that's exactly what I see. Maybe it's my bad that I didn't see the "Failures 1" above, I looked at + clicked the yellow text and there's no indication that the test failed.

**Comment by MikeSchulze** [comment]
Added new project settings to enable/disable orphan reporting.
![image](https://user-images.githubusercontent.com/347037/119259678-9bb6b980-bbcf-11eb-9553-45115ebb3707.png)
