### ISSUE TITLE
GD-69: Add assert_vec2 and assert_vec3 to enable vector validation

### ISSUE THREAD

**Issue by ohin** [MikeSchulze/gdUnit3#69]
Currently, I cannot assert equality or check `var` for `null` if it's value is `Vector2`. `assert_that/assert_object` reports, that `Vector2` is not an Object.

The error reported is this: `line -1: 	 GdUnitObjectAssert inital error, unexpected type <Vector2>`

I am quite new to GDScript, so I don't feel I can suggest good solution, but it looks like new `assert_vec2/3` functions would be nice ;-)

**Comment by MikeSchulze** [comment]
Hi thanks for reporting ;)

assert_object is only for Object based types.
Vector2 and Vector3 is a [ Vector built-in type](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#vector-built-in-types)

Currently no vector type assert exists and will be provided in future.
For now as workaround you can use `assert_float(vec.x).is_equal(3.14)`

**Comment by MikeSchulze** [comment]
added assert_vector2 and assert_vector3 (master)
