### ISSUE TITLE
Are you aware of GUT and WAT testing frameworks?

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit3#7]
I found 3 tools to do unit tests and more.

I use GUT for a while which has a long track record so am reluctant to change tools.

I wonder what your tool does different/better then one of the others.

Your screenshot with progress bar/integration looks better then the GUT scene to run. GUT has a command-line which I use when committing to run all tests. I will study your **integration** part for sure.

### GUT
- https://github.com/bitwes/Gut
- Stats: 655/41
### WAT
- https://github.com/AlexDarigan/WAT-GDScript
- Stats: 142/4
### gdUnit3
- https://github.com/MikeSchulze/gdUnit3
- Stats: 0/0

**Comment by MikeSchulze** [comment]
Hi clenens,
i tested GUT and WAT and i couldn't really get used to it. So i started an half year ago to write my own API. Starting just for fun and get more detailed in the GdScript stuff.

At the end i want to have a modern and easy to use API

Means fully integrated in the editor,
to have **fluentable syntax**
easy navigate to failing tests or create tests
fully mock support to use functions with default arguments, **static** function mocking
spy with **argument matcher** for easyier testing
etc,


I current working on CLI tool, with html report
And Stats: 0/0 sure it is new ;)
