### ISSUE TITLE
GD-80: Get it working with Godot 4.x

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit3#80]
I want so run unit tests on Godot 4.x

**Describe the solution you'd like**
The plugin should be installable and run on newes Godot 4.x version

**Comment by MikeSchulze** [comment]
Stopped at the very beginning Godot 4.x is still a pre-alpha and it is currently not possible to migrate.
e.g. https://github.com/godotengine/godot/issues/47705

**Comment by Psirus** [comment]
Apparently this has been fixed, just FYI.
