### ISSUE TITLE
GD-88: Move internal tests under one directory for easy install exclusion

### ISSUE THREAD

**Issue by cgbeutler** [MikeSchulze/gdUnit3#88]
**Is your feature request related to a problem? Please describe.**
When installing from the AssetLib, you can choose not to install certain folders. What can be excluded is currently unclear and spread out.

**Describe the solution you'd like**
Most of the AssetLib assets have a top-level folder for `examples` and `tests`, making it easy to exclude those folders for a minimal install. It would be nice if we could move all the `test` folders to a common one for easy exclusion. This may also make it easier when updating gdUnit3, as the test folder will likely remain unchanged.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MikeSchulze** [comment]
Hi @cgbeutler thanks for your feedback.

I currently working on a integrated upgrade tool that will solve this problem.
Additional i will check what i can do to exclude tests by default from downloading without break the CI.

**Comment by MikeSchulze** [comment]
On next AssetLib version the test will be excluded see https://github.com/MikeSchulze/gdUnit3/blob/master/.gitattributes
