### ISSUE TITLE
GD-90: Some notes on tag gdUnit3-0.9.5-rc

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit3#90]
**The used Godot version:**

Godot-3.3.2

**OS including version:**

Mac OS Big Sure 11.4

**Describe the bug**

- [ ] This version is not available in the AssetLib
- [ ] The zip contains a directory examples, can we rename that into gdUnit3-examples?
- [ ] Why is there a (extra) plugin directory `GdCommons` which is confusing
  - I thought it was not allowed on https://docs.godotengine.org/en/stable/tutorials/assetlib/uploading_to_assetlib.html but cannot find back.
  - Can we move this into `gdUnit3` directory?
- [ ] Dropping the zip into existing project generates error. See below

I run using a shell script and the terminal shows this error
```
/Applications/Godot_v3.3.2-stable_osx.universal.app/Contents/MacOS/Godot --editor
...
SCRIPT ERROR: GDScript::reload: Parse Error: The identifier "TimeUnit" isn't declared in the current scope.
   At: res://addons/GdCommons/DateTime/src/LocalTime.gd:48.
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583.
```

**Steps to Reproduce**

1. Download ZIP version from github
2. Unzip
3. Drop all files into an existing project
4. Start Godot from command-line
5. Check the script output

**Minimal reproduction project:**

**Comment by clemens-tolboom** [comment]
- There is no quick start on https://github.com/MikeSchulze/gdUnit3/blob/master/README.md (which my brain needs)
  - Enable the plugin from project settings plus other stuff?
  - There is a link to https://github.com/MikeSchulze/gdUnit3/wiki but that is way too low.
  - Both README.md and Wiki shows all features (in your face) ... is that the most important stuff to tell potential/new users?
  - I prefer a short getting started in the README.md and links to (more) features wiki page

**Note** this is my brain dump noting stressores ;-)

**Comment by MikeSchulze** [comment]
Thanks for reporting.

> * [ ]  This version is not available in the AssetLib

Yes it is not published yet

> * [ ]  The zip contains a directory examples, can we rename that into gdUnit3-examples?

Yes, this is a good idea.

> * [ ]  Why is there a (extra) plugin directory `GdCommons` which is confusing

This is a left over and will be moved next into the plugin.
>   * Can we move this into `gdUnit3` directory?

yes

> * [ ]  Dropping the zip into existing project generates error. See below

Uh thats bad, i have to verify.

For the README.md, yes it makes sense to have install instructions and short example here

**Comment by MikeSchulze** [comment]
GdUnit3 v0.9.6-rc should be available in AssetLib in some minutes
