### ISSUE TITLE
assert_str(null).is_equal('blabla')

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit3#91]
**The used Godot version:**
Godot-3.3.2

**OS including version:**
Mac OS Big Sure 11.4

**Describe the bug**

![image](https://user-images.githubusercontent.com/371014/121812190-3f433900-cc67-11eb-9fe8-878545fe7181.png)

The output from `assert_str(null).is_equal('blabla')` is confusing.

The diffing somehow inserts `<Nu` and later `>` in `'b<Nulabla>'`

Diff is done against  **string value ** `<Null>` as colors shows. Same goes for a `Dictionary` but **not** for `Node2D`

I guess using `assert_str` with a non string value should not call internal `_to_string()`.

What do you think?

**Steps to Reproduce**

Run the assert in a test.
```
	assert_str(null).is_equal('blabla')
	assert_str('apple').is_equal('blabla')
	assert_str({}).is_equal('another test')
	assert_str(Node2D.new()).is_equal('tes2ting')
```
**Minimal reproduction project:**

**Comment by MikeSchulze** [comment]
Hi @clemens-tolboom this is not a bug.

The string diff shows characters missing in red and matching characters in green this is the expected behavior.

Using assert_str() is only allowed for String types and using a Dictionary like in your example is not allowed and will print out an error.
For Dictionary testing you have to use `assert_dict()` or assert_that() where is auto typing.
This is described here https://github.com/MikeSchulze/gdUnit3/wiki/Asserts

**Comment by clemens-tolboom** [comment]
Hmmm ... I tried to explain by silly examples. I called a function expecting a string but got `null`. I got confused by the stringification of the `null` or `{}`

> Using assert_str() is only allowed for String types

Guess the func signature could/should then be
```
func assert_str(current:String,
```
which then gives

>  res://test/wp_connectTest.gd:19 - Parse Error: At "assert_str()" call, argument 1. The passed argument's type (null) doesn't match the function's expected argument type (String).

or for Dictionary

>  res://test/wp_connectTest.gd:19 - Parse Error: At "assert_str()" call, argument 1. The passed argument's type (Dictionary) doesn't match the function's expected argument type (String)

Thanks for your quick response :-)

I really like GDUnit but need to learn too much still :-/

**Comment by MikeSchulze** [comment]
Your feedback is always welcome ;)

Yes, the typing is a bit messy, since it does not allow the assignment of null values.
This is the reason why the typed asserts have no typesave argumen
