### ISSUE TITLE
Wiki references to master/examples

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit3#94]
**Describe the bug**

Visiting https://github.com/MikeSchulze/gdUnit3/wiki/advanced_testing#advanced-testing the link to example is wrong. Checking the wiki there are 4 lines.

```
advanced_testing.org:5:The example code can be found here [[examples | https://github.com/MikeSchulze/gdUnit3/tree/master/examples]]
advanced_testing.org:128:The example can be find [[here|https://github.com/MikeSchulze/gdUnit3/blob/master/examples/SignalsTestExamples/test/ExampleMockWithSignalTest.gd]]
advanced_testing.org:171:The example can be find [[here|https://github.com/MikeSchulze/gdUnit3/blob/master/examples/SignalsTestExamples/test/ExampleSpyWithSignalTest.gd]]
advanced_testing.org:293:The example can be find [[here|https://github.com/MikeSchulze/gdUnit3/blob/master/examples/MenuDemo2D/test/GameSpyTest.gd]]
```

For what its worth DRY (Don't repeat yourself) the Wiki could link (only) to the [master/gdUnit-example](https://github.com/MikeSchulze/gdUnit3/tree/master/gdUnit3-examples) ... it would be cool if the wiki could **embed** the examples somehow which keeps our eyes dry too ;-)

**Comment by MikeSchulze** [comment]
Arg yes i forgot to addapt the wiki to the new locations ;)
Thanks for reporting.

**Comment by MikeSchulze** [comment]
fixed
