### ISSUE TITLE
Question about using gdUnit as an API

### ISSUE THREAD

**Issue by Xananax** [MikeSchulze/gdUnit3#95]
We're building a live editor for Godot which runs in the browser and validates custom user code 

We have the editor part working ([tweet of the early proto](https://twitter.com/NathanGDQuest/status/1400893709005230082)), with error reporting and so on, and we're now deciding how to implement validation.

Instead of reinventing the wheel, I'm looking at gdUnit and I think I like what I see, but I am not clear if it can fit the bill.

 I'd have two questions:
 
1. Can gdUnit tests run in the browser (in release mode) and be exported with the project?
2. Is there a small example about how we could use gdUnit from our own custom code, as an API, rather than a full harness? An example case: when a user presses a button, I would like to run a series of tests on a scene's sprites, collect the results, and display them to the user. Again, to be clear, the user in this case is a student, and this is happening in an exported project

**Comment by MikeSchulze** [comment]
Hello, thank you for the interest and the look into my project
> 
> 1. Can gdUnit tests run in the browser (in release mode) and be exported with the project?

Generally it should be possible to run inside a browser, the code is 99% pure GdScript (running in a browser I never tested).
Currently the release mode is run "externally" and has no debug information, e.g. error lines.
But I suspect that in your use case you need the debug mode inside the editor to get the full report including error lines.

> 2. Is there a small example about how we could use gdUnit from our own custom code, as an API, rather than a full harness? An example case: when a user presses a button, I would like to run a series of tests on a scene's sprites, collect the results, and display them to the user. Again, to be clear, the user in this case is a student, and this is happening in an exported project

GdUnit was not designed as an API for third party systems but it should in principle be possible via a custom executor to run dynamic generated tests.
The best example would be res://addons/gdUnit3/bin/GdUnitCmdTool.gd, which is a runner with an executor that executes test suites controlled by arguments and collects the reports and saves them as HTML.
If I understand you correctly, you want to run tests from a predefined scene?
So you have the test cases already in your head and you could use predefined 
TestSuites depending on the use case.

If you have any further questions, please contact me.
