### ISSUE TITLE
GD-99: Console shows errors when install GdUnit3 *v0.9.6-rc* over the AssetLib

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit3#99]
**The used Godot version:** 3.3.2.stable
**OS including version:** Mac
**Describe the bug**

1. When download and install through the AssetLib I see some (6) `- drivers/unix/file_access_unix.cpp:279 - Condition "!p_src" is true.`
2. 

**Steps to Reproduce**

**Minimal reproduction project:**

**Comment by MikeSchulze** [comment]
@clemens-tolboom can you please add the full log of starting the plugin?

**Comment by MikeSchulze** [comment]
After a lot of trying by reducing the files during installation, I found out that the installation via AssetLib has problems with zero byte length files.
